console.log('Stratus ready to go')

var newData = [
  {"ID": "T1156", "name": ".bash_profile and .bashrc", "properties": ['T1156', '~/\\.bash_profile', '~/\\.bashrc', 'Terminal.app', 'bash_profile', 'bashrc'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1134", "name": "Access Token Manipulation", "properties": ['T1134', 'DuplicateToken', 'ImpersonateLoggedOnUser', 'SetThreadToken', 'CreateProcessWithTokenW', 'WTSQueryUserToken', 'NtFilterToken', 'CreateProcessAsUserA', 'Invoke-TokenManipulation', 'SsIMM'], "stem": ['access (?:token|token[\w]) manipul[\\w]+'], "keyword": [], "support": []},
  {"ID": "T1087", "name": "Account Discovery", "properties": ['T1087', 'localgroup', 'dscl', 'dscacheutil', 'passwd', 'dsquery', 'master.passwd', 'Privesc-PowerUp'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1182", "name": "AppCert DLLs", "properties": ['T1182', 'AppCertDLLs', 'HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Session', 'CreatePrcess', 'CreateProcessAsUser', 'CreateProcessWithLogonW', 'CreateProcessWithTokenW', 'WinExec', 'AppCertDLL', 'AppCert'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1103", "name": "AppInit DLLs", "properties": ['T1103', 'AppInit_DLLs', 'HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows', 'NT\\CurrentVersion\\Windows', 'HKEY_LOCAL_MACHINE\\Software\\Wow6432Node\\Microsoft\\Windows', 'user32\\.dll', 'AppInit', 'RegCreateKeyEx', 'RegSetValueEx'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1155", "name": "AppleScript", "properties": ['T1155', 'AppleEvent', 'AppleScript', 'osascript', 'osalang'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1138", "name": "Application Shimming", "properties": ['T1138', 'shim', 'shims', 'sdbinst\\.exe', '\\AppPatch\\sysmain.sdb', 'sysmain.sdb', 'hklm\\software\\microsoft\\windows nt\\currentversion\\appcompatflags\\installedsdb', 'sdb|[\\w]+\\.sdb|\\.sdb', 'RedirectEXE', 'InjectDLL', 'DisableNX', 'DisableSEH', 'GetProcAddress'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1123", "name": "Audio Capture", "properties": ['T1123', 'microphon[\\w]+', 'Get-MicrophoneAudio'], "stem": [], "keyword": ['audio'], "support": ['captur[\\w]+|collect|collect[\\w]+|grab|seiz[\\w]+|record|record[\\w]+']},
  {"ID": "T1131", "name": "Authentication Package", "properties": ['T1131', 'Authentication package', 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa', 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\RunAsPPL'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1020", "name": "Automated Exfiltration", "properties": ['T1020'], "stem": ['(?:automat[\\w]+|schedul[\\w]+) exfiltra[\\w]+'], "keyword": [], "support": []},
  {"ID": "T1197", "name": "BITS Jobs", "properties": ['T1197', 'BITSAdmin', 'HKEY_LOCAL_MACHINE\\Software\\Policies\\Microsoft\\Windows\\BITS'], "stem": ['bit (?:job|job[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1139", "name": "Bash History", "properties": ['T1139', '\\.bash_history', '~/\\.bash_history', 'bash_history'], "stem": ['bash histor[\\w]+'], "keyword": [], "support": []},
  {"ID": "T1067", "name": "Bootkit", "properties": ['T1067', 'MBR', 'bootkit[\\w]+'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1110", "name": "Brute Force", "properties": ['T1110', 'BruteForcer', 'brute', 'spraying'], "stem": ['brute forc[\\w]+', 'password (?:attack|attack[\\w]+)', 'password (?:spray|spray[\\w]+)', 'diction[\\w]+ (?:attack|attack[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1088", "name": "Bypass User Account Control", "properties": ['T1088'], "stem": ['bypass user account control'], "keyword": [], "support": []},
  {"ID": "T1191", "name": "CMSTP", "properties": ['T1191', 'CMSTP\\.exe', 'CMSTP'], "stem": ['connect[\\w]+ manag[\\w]+ profil[\\w]+ instal[\\w]+'], "keyword": [], "support": []},
  {"ID": "T1500", "name": "Compile After Delivery", "properties": ["T1500", "Compile(|d) after delivery", "compile(?:|[\\w]+) (?:before |and |)execut[\\w]+"], "stem": [], "keyword": [], "support": []},
  {"ID": "T1042", "name": "Change Default File Association", "properties": ['T1042', 'Assoc'], "stem": ['change default file association'], "keyword": [], "support": []},
  {"ID": "T1146", "name": "Clear Command History", "properties": ['T1146', 'HISTFILE', 'HISTFILESIZE=0'], "stem": ['clear command history'], "keyword": [], "support": []},
  {"ID": "T1115", "name": "Clipboard", "properties": ['T1115', 'Catchamas', 'clipboard', 'pbpaste'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1059", "name": "Command-Line Interface", "properties": ['T1059', 'cmd', 'cmd\\.exe', 'command(?: |-|)line(?:|[\\w]+)'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1043", "name": "Commonly Used Port", "properties": ['T1043'], "stem": ['(?:port|tcp|udp)(?: |)(?:21|22|25|26|53|80|110|443|3389|8080|8443)'], "keyword": ['port|ports', 'communicat[\\w]+', 'tcp|udp'], "support": ['(?:21|22|25|26|53|80|110|443|3389|8080|8443)']},
  {"ID": "T1223", "name": "Complied HTML File", "properties": ['T1223', '[\\w]+\\.chm|\\.chm', 'CHM', 'hh\\.exe'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1090", "name": "Connection Proxy", "properties": ['T1090', 'FLIPSIDE', 'Gazer', 'netsh', '(?:tunnel|tunnel[\\w]+)', 'prox[\\w]+', 'HTRAN', 'ZXProxy', 'ZXPortMap'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1196", "name": "Control Panel Item", "properties": ['T1196', 'CPL', '[\\w]+\\.cpl|\\.cpl', 'CPlApplet'], "stem": ['control panel'], "keyword": [], "support": []},
  {"ID": "T1003", "name": "Credential Dumping", "properties": ['T1003', 'credential dumping', 'pwdumpx\\.exe', 'gsecdump', 'Mimikatz', 'HKLM\\sam', 'Creddump7', 'DCC2', 'reg\\.exe', 'PBKDF2', 'NTDS\\.dit', '\\NTDS\\Ntds\\.dit', 'secretsdump\\.py', 'Invoke-NinjaCopy', 'post/windows/gather/credentials/gpp', 'Get-GPPPassword', 'CredSSP', 'procdump', 'sekurlsa', 'lsassdump\\.dmp', 'DCSync', 'lsadump', 'NetSync', 'MimiPenguin'], "stem": ['secur[\\w]+ account[\\w]+ manag[\\w]+', 'lsa[\\w]+ secret[\\w]+', 'group[\\w]+ polici[\\w]+ prefer[\\w]+'], "keyword": ['credenti[\\w]+', 'inform[\\w]+', 'user|users', 'password|passwords', 'authent[\\w]+'], "support": ['cach[\\w]+', 'store|store[\\w]+', 'dump|dump[\\w]+']},
  {"ID": "T1485", "name": "Data Destruction", "properties": ["T1485", "data (?:destruct[\\w]+|delet[\\w]+)", "wiper(?:|s)"], "stem": ["(?:destro[\\w]+|overwrit[\\w]+|delet[\\w]+) (?:a |the |)(?:data|file(?:|s))"], "keyword": [], "support": []},
  {"ID": "T1486", "name": "Data Encrypted for Impact", "properties": ["T1486", "ransomware(?:|s)"], "stem": ["encryp[\\w]+ (?:of |user(?:|.s|s) |victi[\\w]+ |)(?:file(?:|s)|documen[\\w]+)"], "keyword": [], "support": []},
  {"ID": "T1207", "name": "DCShadow", "properties": ['T1207', 'DCShadow', 'nTDSDSA'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1491", "name": "Defacement", "properties": ["T1491", "deface|defacemen[\\w]+|defaci[\\w]+"], "stem": [], "keyword": [], "support": []},
  {"ID": "T1488", "name": "Disk Content Wipe", "properties": ["T1488", "disk content(?:s|) wipe"], "stem": ["(?:overwrit[\\w]+|destro[\\w]+|wipe(?:|s))\\W+(?:\\w+\\W+){0,6}?(?!file(?:|s))drive(?:|s)"], "keyword": [], "support": []},
  {"ID": "T1487", "name": "Disk Structure Wipe", "properties": ["T1487", "data structure wipe(|d)"], "stem": ["(?:overwrit[\\w]+|destro[\\w]+|wipe(?:|s))\\W+(?:\\w+\\W+){0,4}?(?!file(?:|s))(?:MBR|Master Boot Record|disk(partition(?:|s)|structure(?:|s)))"], "keyword": [], "support": []},
  {"ID": "T1038", "name": "DLL Search Order Hijacking", "properties": ['T1038', 'Downdelph'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1073", "name": "DLL Side-Loading", "properties": ['T1073', 'WinSxS'], "stem": ['(?:dll|dll[\\w]+) side-load[\\w]+', '(?:dll|dll[\\w]+) side (?:load|load[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1002", "name": "Data Compressed", "properties": ['T1002', '7zip', 'RAR', 'ZIP', 'zlib', 'Lempel-Ziv-Welch', 'Lurid'], "stem": ['(?:data|data[\\w]+) compress[\\w]+'], "keyword": [], "support": []},
  {"ID": "T1132", "name": "Data Encoding", "properties": ['T1132', 'ASCII', 'Unicode', 'Base64', 'UTF-8', 'Binary-to-text', 'gzip', 'encoded', 'Base64-encoded'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1022", "name": "Data Encrypted", "properties": ['T1022', 'encryption', '3DES', 'AES', 'cipher'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1074", "name": "Data Staged", "properties": ['T1074'], "stem": ['data staged', 'stored before exfiltra[\\w]+'], "keyword": [], "support": []},
  {"ID": "T1030", "name": "Data Transfer Size Limits", "properties": ['T1030'], "stem": ['data transfer size limi[\\w]+'], "keyword": ['exfiltrat[\\w]+|send|communic[\\w]+|uploa[\\w]+'], "support": ['(?:[0-9]+|limi[\\w]+)(?: |-|)(?:byte|bytes|bits|kb)']},
  {"ID": "T1213", "name": "Data from Information Repositories", "properties": ['T1213', 'spwebmember', 'Ke3chang'], "stem": ['(?:data|informat[\\w]+) from (?:repositor[\\w]+|resources|sharepoint|microsof[\\w]+ sharepoint|github)'], "keyword": ['repositor[\\w]+', 'resources', 'sharepoint', 'github'], "support": []},
  {"ID": "T1005", "name": "Data from Local System", "properties": ['T1005'], "stem": ['data from local (?:system|systems)', '(?:data|file|files|documen[\\w]+) from (?:the |)(?:victi[\\w]+ |use[\\w]+ |)(?:local syste[\\w]+|director[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1039", "name": "Data from Network Shared Drive", "properties": ['T1039', 'SMB', 'FTP'], "stem": ['network shar[\\w]+ driv[\\w]+', '(?:file|mapped) (?:shares|server)', '(?:data|file|files|documen[\\w]+) from (?:a |)(?:networ[\\w]+ file |file |networ[\\w]+ shared |networ[\\w]+ |mapped |)(?:driv[\\w]+|remote syste[\\w]+|server)'], "keyword": [], "support": []},
  {"ID": "T1027", "name": "Obfuscated Files or Information", "properties": ['T1027', 'T1140', 'T1001', 'T1022', 'T1132', 'stenography', 'Base64', 'encryption', 'encrypted', 'deobfuscated', 'Obfuscated', 'Obfuscation', 'deobfuscation', 'decode', 'certutil'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1140", "name": "Deobfuscated/Decode Files or Information", "properties": ['T1140', 'T1027', 'deobfuscated', 'Obfuscated', 'Obfuscation', 'deobfuscation', 'decode', 'certutil'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1089", "name": "Disabling Security Tools", "properties": ['T1089', 'SsIMM'], "stem": [], "keyword": ['security', 'mcafe', 'epo', 'anti-virus', 'antivirus'], "support": ['disabl[\\w]+', 'incapacit[\\w]+', 'debilit[\\w]+', 'paralyz[\\w]+']},
  {"ID": "T1175", "name": "Distributed Component Object Model", "properties": ['T1175', 'Dcomcnfg\\.exe', 'DCOM', 'middleware'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1172", "name": "Domain Frontng", "properties": ['T1172', 'SNI field'], "stem": ['domain fronting', '(?:manipul[\\w]|change|)(?: of| to|) HTTP header'], "keyword": [], "support": []},
  {"ID": "T1483", "name": "Domain Generation Algorithms", "properties": ["T1483", "Domain Generation Algorithms", "DGA(?:|s)"], "stem": [], "keyword": [], "support": []},
  {"ID": "T1482", "name": "Domain Trust Discovery", "properties": ["T1482", "Domain Trust Discovery"], "stem": ["DSEnumerateDomainTrusts()", "Get-NetDomainTrust", "Get-NetForestTrust", "domain trust(?:|s)", "enumerat[\\w]+ trust(?:|[\\w]+) domain(?:|s)"], "keyword": [], "support": []},
  {"ID": "T1157", "name": "Dylib Hijacking", "properties": ['T1157', '(?:dylib|dylib[\\w]+)'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1173", "name": "Dynamic Data Exchange", "properties": ['T1173', 'DDE'], "stem": ['dynam[\\w]+ data exchang[\\w]+'], "keyword": [], "support": []},
  {"ID": "T1114", "name": "Email Collection", "properties": ['T1114'], "stem": ['email collec[\\w]+'], "keyword": ['email', '[\\w]\\.pst|\\.pst', '[\\w]\\.ost|\\.ost', 'Outlook', 'GETMAIL', 'mail', 'imap', 'pop3', 'smtp', 'ost', 'pst', 'webmail'], "support": ['captur[\\w]+', 'collect|collect[\\w]+', 'grab', 'seiz[\\w]+', 'record|record[\\w]+']},
  {"ID": "T1499", "name": "Endpoint Denial of Service", "properties": ["T1499", "Denial of Service", "DoS", "DDoS"], "stem": ["OS Exhaustion Flood", "(?:SYN|ACK|HTTP|(?:Service|Application) Exhaustion) Flood", "SSL Renegotiation Attack"], "keyword": ["Denial of Service|DoS|DDoS"], "support": ["(?:application|system) Exploitation"]},
  {"ID": "T1480", "name": "Execution Guardrails", "properties": ["T1480", "execution guardrail(?:|s)", "environmen[\\w]+ key(?:|s|ing(?:|s))"], "stem": [], "keyword": [], "support": []},
  {"ID": "T1106", "name": "Execution through API", "properties": ['T1106', 'API', '(?:CreateProcess|CreateProcess[\\w]+)', 'CreateProcessAsUser[\\w]+', 'CreateProcessInternal[\\w]+', 'CreateProcessWithLogonW', 'CreateProcessWithTokenW', '(?:LoadLibrary|LoadLibrary[\\w]+)', 'LoadModule', 'LoadPackagedLibrary', 'ShellExecute[\\w]+'], "stem": ['execut[\\w]+ through API', 'Windows API (?:calls|call|functio[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1129", "name": "Execution through Module Load", "properties": ['T1129', 'NTDLL\\.dll', 'CreateProcess', 'LoadLibrary'], "stem": ['(?:load|loads)[^\\.:]+DLL'], "keyword": [], "support": []},
  {"ID": "T1048", "name": "Exfiltration Over Alternative Protocol", "properties": ['T1048', 'FTP', 'SMTP', 'HTTP', 'HTTPS', 'DNS', 'FTP', 'SMTP', 'HTTP/S', 'DNS'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1041", "name": "Exfiltration Over Command and Control Channel", "properties": ['T1041'], "stem": ['(?:exfiltrat[\\w]+|send|communic[\\w]+|uploa[\\w]+)(?: of|the|)(?: data| file| files| documen[\\w]+| informat[\w]+|)[^\\.:]+(?:C2|C&C|command and control)'], "keyword": [], "support": []},
  {"ID": "T1011", "name": "Exfiltration Over Other Network Medium", "properties": ['T1011', 'bluetooth'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1052", "name": "Exfiltration Over Physical Medium", "properties": ['T1052', 'USBStealer'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1190", "name": "Exploit Public-Facing Application", "properties": ['T1190', 'SQLi', 'sqlmap'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1212", "name": "Exploitation for Credential Access", "properties": ['T1212', 'MS14-068'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1211", "name": "Exploitation for Defense Evasion", "properties": ['T1211'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1210", "name": "Exploitation for Remote Services", "properties": ['T1210', 'SMB', 'RDP'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1046", "name": "Network Service Scanning", "properties": ['T1046', 'scanning', 'osql\\.exe', 'nmap', 'Acunetix', 'OpenVAS', 'Wireshark', 'ping', 'shodan|shodan\\.io'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1133", "name": "External Remote Services", "properties": ['T1133', '(?:VPN|VPN[\\w]+)', 'Citrix'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1181", "name": "Extra Window Memory Injection", "properties": ['T1181', 'EWM'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1008", "name": "Fallback Channels", "properties": ['T1008'], "stem": ['fallback channe[\\w]+'], "keyword": ['fallback', 'altern[\\w]+', 'backup', 'subsitut[\\w]+', 'another', 'back-up', 'redund[\\w]+'], "support": ['channel|channels', 'communic[\\w]+', 'c2', 'c&c', 'node', 'prox[\\w]+', 'traffic', 'connectio[\\w]+', 'transfer[\\w]+']},
  {"ID": "T1107", "name": "File Deletion", "properties": ['T1107', 'cleanup', 'del', 'erase', 'delet[\\w]+', 'Sysinternals', 'SDelete'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1222", "name": "File Permission Modification", "properties": ['T1222', 'DACLs', 'DACL', 'Icacls1', 'Icacls2', 'cacls\\.exe', 'takeown', 'Set-Acl', 'chmod', 'chown'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1006", "name": "File System Logical Offsets", "properties": ['T1006'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1044", "name": "File System Permissions Weakness", "properties": ['T1044'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1495", "name": "Firmware Corruption", "properties": ["T1495", "firmware corruption"], "stem": ["(?:overwrite[\\w]+|corrup[\\w]+|wipe)\\W+(?:\\w+\\W+){0,6}?(?:BIOS|firmware(?:|s)|hard drive(?:|s)|motherboard(?:|s)|video card(?:|s))"], "keyword": [], "support": []},
  {"ID": "T1187", "name": "Forced Authentication", "properties": ['T1187'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1144", "name": "Gatekeeper Bypass", "properties": ['T1144'], "stem": ['gatekepp[\\w]+ (?:bypass|bypass[\\w]+)'], "keyword": ['gatekeep[\\w]+'], "support": ['bypass|bypass[\\w]+', 'workaro[\\w]+']},
  {"ID": "T1061", "name": "Graphical User Interface", "properties": ['T1061', 'GUI'], "stem": ['(?:graphic|graphic[\\w]+) user interfac[\\w]+'], "keyword": [], "support": []},
  {"ID": "T1484", "name": "Group Policy Modification", "properties": ["T1484", "Group Policy (?:Object(?:|s)|Modification(?:|s)|Settin[\\w]+)"], "stem": ["(?:modif[\\w]+|alter(?:|[\\w]+)|chang[\\w]+)\\W+(?:\\w+\\W+){0,2}?GPO(?:|s)"], "keyword": [], "support": []},
  {"ID": "T1148", "name": "HISTCONTROL", "properties": ['T1148', 'HISTCONTROL', 'ignoredups'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1158", "name": "Hidden Files and Directories", "properties": ['T1158', 'attrib\\.exe', 'attrib'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1147", "name": "Hidden Users", "properties": ['T1147', 'Hide500Users', 'HideUser'], "stem": ['hidden (?:user|users|account|accounts)'], "keyword": [], "support": []},
  {"ID": "T1143", "name": "Hidden Window", "properties": ['T1143', 'apple\\.awt\\.UIElement'], "stem": ['hidden windo[\\w]+'], "keyword": ['hidden|invisible'], "support": ['window|windows', 'popup|popups', 'screen|screens']},
  {"ID": "T1179", "name": "Hooking", "properties": ['T1179', 'hooking', 'IAT'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1062", "name": "Hypervisor", "properties": ['T1062', 'hypervisor'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1183", "name": "Image File Execution Options Injection", "properties": ['T1183', 'IFEO'], "stem": ['Image File Execution (?:Option|Options) (?:Inject|Inject[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1490", "name": "Inhibit System Recovery", "properties": ["T1490", "(?:inhibit|delete|corrup[\\w]+|disabl[\\w]+)(?:| operating) system recovery"], "stem": ["delete(?:|s) shadow(?:|s)(?: copies|)", "shadowcopy delete"], "keyword": [], "support": []},
  {"ID": "T1070", "name": "Indicator Removal on Host", "properties": ['T1070', 'wevtutil', 'SDelete', 'var/logs', '/var/logs'], "stem": ['indicator removal', 'remove indicator(?:|s)'], "keyword": [], "support": []},
  {"ID": "T1202", "name": "Indirect Command Execution", "properties": ['T1202', 'Forfiles', 'pcalua\\.exe'], "stem": ['indirect command execut[\\w]+'], "keyword": [], "support": []},
  {"ID": "T1056", "name": "Input Capture", "properties": ['T1056', 'keystrokes', 'keylogging', 'Get-Keystrokes'], "stem": [], "keyword": ['input|inputs', 'data', 'post', 'credenti[\\w]+', 'informat[\\w]+', 'respons[\\w]+', 'keystrok[\\w]+'], "support": ['captur[\\w]+', 'collect|collect[\\w]+', 'grab', 'seiz[\\w]+', 'record|record[\\w]+']},
  {"ID": "T1130", "name": "Install Root Certificate", "properties": ['T1130', 'trustRoot'], "stem": ['root certif[\\w]+'], "keyword": [], "support": []},
  {"ID": "T1118", "name": "InstallUtil", "properties": ['T1118', 'InstallUtil|InstallUtil\\.exe'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1208", "name": "Keberoasting", "properties": ['T1208', 'SPNs', '(?:Kerberoast|Kerberoast[\\w]+)', 'TGT', 'TGS', 'InvokeKerberoast', 'TGS-REP', 'Invoke-Kerberoast'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1215", "name": "Kernel Modules and Extensions", "properties": ['T1215', 'LKMs', '(?:rootkit|rootkit[\\w]+)', 'Phalanx2', 'Diamorphine', 'LKM', 'kext', 'kextload', 'kextunload', 'rkhunter', 'chrookit'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1142", "name": "Keychain", "properties": ['T1142', 'keychain', '~/Library/Keychains/', '/Library/Keychains/', '/Network/Library/Keychains/'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1161", "name": "LC_LOAD_DYLIB Additions", "properties": ['T1161', 'LC_LOAD_DYLIB', 'LC_CODE_SIGNATURE'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1149", "name": "LC_MAIN Hijacking", "properties": ['T1149', 'LC_MAIN', 'LC_THREAD', 'LC_UNIXTHREAD'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1171", "name": "LLMNR/NBT-NS Poisoning", "properties": ['T1171', 'LLMNR', 'NBT-NS', '/NBT-NS', 'NBNSpoof'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1159", "name": "Launch Agent", "properties": ['T1159', 'launchd', '/System/Library/LaunchAgents', '/Library/LaunchAgents', 'HOME/Library/LaunchAgents', 'OSX\\.Dok'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1160", "name": "Launch Daemon", "properties": ['T1160', 'daemon', '/System/Library/LaunchDaemons', '/Library/LaunchDaemons', 'LaunchDaemons'], "stem": ['launch (?:daemon|daemon[\\w]+)'], "keyword": ['daemon|daemons'], "support": ['launch|launch[\\w]+', 'call|calls', 'initi[\\w]+']},
  {"ID": "T1152", "name": "Launchctl", "properties": ['T1152', 'Launchctl', 'launchd'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1015", "name": "Accessibility Features", "properties": ['T1015', 'sethc\\.exe', 'C:\\Windows\\System32\\sethc\\.exe', 'utilman\\.exe', 'magnifer', 'narrator'], "stem": ['accessibil[\\w]+ featur[\\w]+'], "keyword": [], "support": []},
  {"ID": "T1098", "name": "Account Manipulation", "properties": ['T1098'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1017", "name": "Application Deployment Software", "properties": ['T1017'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1010", "name": "Application Window Discovery", "properties": ['T1010'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1119", "name": "Automated Collection", "properties": ['T1119'], "stem": ['automat[\\w]+ collec[\\w]+'], "keyword": [], "support": []},
  {"ID": "T1009", "name": "Binary Padding", "properties": ['T1009'], "stem": ['binary (?:pad|pad[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1217", "name": "Browser Bookmark Discovery", "properties": ['T1217', 'bookmark'], "stem": ['(?:browser|browser[\\w]+) (?:bookmark|bookmark[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1176", "name": "Browser Extensions", "properties": ['T1176', '(?:plugin|plugins)'], "stem": [], "keyword": ['browser', 'chrome', 'edge', 'internet', 'explorer', 'firefox'], "support": ['extens[\\w]+', 'plugin', 'plug-in', 'plug']},
  {"ID": "T1116", "name": "Code Signing", "properties": ['T1116'], "stem": ['code (?:sign|sign[\\w]+)'], "keyword": ['sign|sign[\\w]+'], "support": ['code', 'certif[\\w]+']},
  {"ID": "T1092", "name": "Communication Through Removable Media", "properties": ['T1092'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1109", "name": "Component Firmware", "properties": ['T1109'], "stem": ['componen[\\w]+ firmwar[\\w]+'], "keyword": ['firmware'], "support": ['additio[\\w]+']},
  {"ID": "T1122", "name": "Component Object Model Hijacking", "properties": ['T1122'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1136", "name": "Create Account", "properties": ['T1136'], "stem": ['net user'], "keyword": ['creat[\\w]+', 'new', 'contriv[\\w]+'], "support": ['account|accounts', 'credenti[\\w]+', 'user|users']},
  {"ID": "T1081", "name": "Credential in Files", "properties": ['T1081'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1214", "name": "Credential in Registry", "properties": ['T1214'], "stem": ['(?:credentia[\\w]+|accoun[\\w]+|user|users) in registr[\\w]+', 'reg'], "keyword": ['registr[\\w]+', 'hkey_local_machin', 'hklm', 'hkey_current_config', 'hkcc', 'hkey_current_root', 'hkcr', 'hkey_us', 'hku', 'hkey_current_us', 'hkcu', 'hkey_performance_data', 'hkey_dyn_data'], "support": ['credenti', 'inform', 'user', 'password', 'authent']},
  {"ID": "T1094", "name": "Custom Command and Control Protocol", "properties": ['T1094'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1024", "name": "Custon Cryptographic Protocol", "properties": ['T1024'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1001", "name": "Data Obfuscation", "properties": ['T1001', 'stenography', 'Base64', 'obfuscat[\\w]+'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1025", "name": "Data from Removable Media", "properties": ['T1025', 'USB'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1189", "name": "Drive-by Compromise", "properties": ['T1189', 'adware', 'inbrowser', 'XSS'], "stem": ['(?:cross-site|cross site) (?:script|script[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1203", "name": "Exploitation for Client Execution", "properties": ['T1203'], "stem": ['arbitar[\\w]+ code execut[\\w]+'], "keyword": [], "support": []},
  {"ID": "T1068", "name": "Exploitation for Privilege Escalation", "properties": ['T1068', 'privesc', 'gsecdump', 'fgdump', 'pwdump', 'hobocopy'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1028", "name": "Windows Remote Management", "properties": ['T1028', 'WinRM'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1083", "name": "File and Directory Discovery", "properties": ['T1083', 'dir', 'tree', 'ls'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1076", "name": "Remote Desktop Protocol", "properties": ['T1076', 'RDP', 'RDS', 'teamviewer'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1200", "name": "Hardware Additions", "properties": ['T1200'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1014", "name": "Rootkit", "properties": ['T1014', 'T1215', '(?:rootkit|rootkits)', 'Phalanx2', 'Diamorphine', '(?:LKM|LKMs)', 'kext', 'kextload', 'kextunload', 'rkhunter', 'chrookit'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1054", "name": "Indicator Blocking", "properties": ['T1054'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1066", "name": "Indicator Removal From Tools", "properties": ['T1066'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1141", "name": "Input Prompt", "properties": ['T1141'], "stem": ['(?:input|user|credentia[\\w]+) prompt'], "keyword": [], "support": []},
  {"ID": "T1177", "name": "LSASS Driver", "properties": ['T1177', 'LSASS', 'T1073', 'T1038'], "stem": [], "keyword": ['lsass'], "support": ['driver|drivers']},
  {"ID": "T1168", "name": "Local Job Scheduling", "properties": ['T1168', 'cron', 'cron\\.d', 'launchd', 'crontab', 'cronjob'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1162", "name": "Login Item", "properties": ['T1162', 'loginitem', 'SMLoginItemSetEnabled'], "stem": ['login (?:item|items)'], "keyword": [], "support": []},
  {"ID": "T1037", "name": "Logon Script", "properties": ['T1037', 'HKCU\\Environment\\UserInitMprLogonScript'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1185", "name": "Man in the Browser", "properties": ['T1185', 'SeDebugPrivilege', 'man-in-the-browser'], "stem": ['(?:man|men) in the (?:browser|browser[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1036", "name": "Masquerading", "properties": ['T1036', 'masquerad[\\w]+'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1031", "name": "Modify Existing Service", "properties": ['T1031', 'sc\\.exe'], "stem": ['modif[\\w]+ exis[\\w]+ servic[\\w]+'], "keyword": ['modifi[\\w]+', 'adapt|adapt[\\w]+', 'chang[\\w]+', 'adjust|adjust[\\w]+', 'inject|inject[\\w]+', 'rework|rework[\\w]+', 'mutat[\\w]+', 'convert|convert[\\w]+', 'alter|alters'], "support": ['servic[\\w]+', 'program|program[\\w]+', 'executa[\\w]+', 'command|command[\\w]+', 'registr[\\w]+']},
  {"ID": "T1112", "name": "Modify Registry", "properties": ['T1112'], "stem": ["(?:modif[\\w]+|adap[\\w]+|change(?:|s))(?: the| a|) registry"], "keyword": [], "support": []},
  {"ID": "T1170", "name": "Mshta", "properties": ['T1170', 'Mshta\\.exe', '[\\w+].hta|\\.hta', 'mshta', 'HTA'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1104", "name": "Multi-Stage Channels", "properties": ['T1104'], "stem": ["multi(?:-| )stage channel(?:|s)"], "keyword": [], "support": []},
  {"ID": "T1188", "name": "Multi-hop Proxy", "properties": ['T1188', "TOR", "onion (?:router|routing)"], "stem": ["multi(?:-| )hop prox[\\w]+"], "keyword": [], "support": []},
  {"ID": "T1026", "name": "Multiband Communication", "properties": ['T1026'], "stem": ["multiband communication"], "keyword": [], "support": []},
  {"ID": "T1079", "name": "Multilayer Encryption", "properties": ['T1079', '(?:tunnel|tunnel[\\w]+)'], "stem": ["multilayer encrypt[\\w]+"], "keyword": [], "support": []},
  {"ID": "T1096", "name": "NTFS File Attributes", "properties": ['T1096', 'NTFS', 'MFT', 'ADS'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1128", "name": "Netsh Helper DLL", "properties": ['T1128', 'Netsh\\.exe', 'Netshell', 'Netsh', 'HKLM\\SOFTWARE\\Microsoft\\Netsh'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1498", "name": "Network Denial of Service", "properties": ["Network (?:Denial of Service|DDoS|(?:distributed |)DoS)"], "stem": ["direct network flood", "(?:udp|ICMP) flood", "(?:reflection|DNS|NTP) amplication"], "keyword": [], "support": []},
  {"ID": "T1126", "name": "Network Share Connection Removal", "properties": ['T1126'], "stem": ["network share(?:|s) connection(?:|s) removal"], "keyword": [], "support": []},
  {"ID": "T1135", "name": "Network Share Discovery", "properties": ['T1135', 'SMB', '\\remotesystem', 'remotesystem'], "stem": ["network share(?:|s) connection(?:|s)"], "keyword": [], "support": []},
  {"ID": "T1040", "name": "Network Sniffing", "properties": ['T1040', 'sniff[\\w]+'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1050", "name": "New Service", "properties": ['T1050'], "stem": ["new service"], "keyword": [], "support": []},
  {"ID": "T1137", "name": "Office Application Startup", "properties": ['T1137', 'Normal\\.dotm', 'Personal\\.xlsb', 'HKEY_CURRENT_USER\\Software\\Microsoft\\Office'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1075", "name": "Pass the Hash", "properties": ['T1075', 'PtH', 'pass-the-hash'], "stem": ['(?:pass|pass[\\w]+) the hash', 'pass-the-hash[\\w]+'], "keyword": [], "support": []},
  {"ID": "T1097", "name": "Pass the Ticket", "properties": ['T1097', 'PtT', 'pass-the-ticket'], "stem": ['(?:pass|pass[\\w]+) the (?:ticket|ticket[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1174", "name": "Password Filter DLL", "properties": ['T1174'], "stem": ["(?:password(?:|'s|s) filter (?:dll|dynamic))"], "keyword": [], "support": []},
  {"ID": "T1201", "name": "Password Policy Discovery", "properties": ['T1201', 'pwpolicy', 'getaccountpolicies', 'common-password'], "stem": ["password polic[\\w]+ discovery"], "keyword": [], "support": []},
  {"ID": "T1034", "name": "Path Interception", "properties": ['T1034'], "stem": ["path interception"], "keyword": [], "support": []},
  {"ID": "T1120", "name": "Peripheral Device Discovery", "properties": ['T1120'], "stem": ["peripheral device(?:|s) discovery"], "keyword": [], "support": []},
  {"ID": "T1069", "name": "Permission Groups Discovery", "properties": ['T1069', 'localgroup', 'dscacheutil', 'dscl', 'ldapsearch'], "stem": ["permission(?:|s) group(?:|s) discovery"], "keyword": ["permission(?:|s) group"], "support": ["discovery"]},
  {"ID": "T1150", "name": "Plist Modification", "properties": ['T1150', 'plist', '[\\w]+.plist|\\.plist'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1205", "name": "Port Knocking", "properties": ['T1205', 'knocking'], "stem": ['(?:port|port[\\w]+) (?:knock|knock[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1013", "name": "Port Monitors", "properties": ['T1013', 'spoolsv\\.exe', 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Print\\Monitors'], "stem": ['(?:port|port[\\w]+) (?:monitor|monitor[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1086", "name": "PowerShell", "properties": ['T1086', 'PowerShell', 'cmdlet'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1145", "name": "Private Keys", "properties": ['T1145', 'SSH', '[\\w]+\\.key|\\.key', '[\\w]+\\.pgp|\\.pgp', '[\\w]+\\.gpg|\\.gpg', '[\\w]+.ppk|\\.ppk', '[\\w]+.p12|\\.p12', '[\\w]+\\.pem|\\.pem', '[\\w]+\\.pfx|\\.pfx', '[\\w]+\\.cer|\\.cer', '[\\w]+\\.p7b|\\.p7b', '[\\w]+\\.asc|\\.asc', '[\\w]+\\.ssh|\\.ssh'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1057", "name": "Process Discovery", "properties": ['T1057', 'task(?:| )list'], "stem": ["process discovery"], "keyword": [], "support": []},
  {"ID": "T1186", "name": "Process Doppelganging", "properties": ['T1186', 'Doppelganging', 'Doppelg.nging', 'NtUnmapViewOfSection', 'VirtualProtectEx', 'SetThreadContext'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1093", "name": "Process Hollowing", "properties": ['T1093', 'hollowing'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1055", "name": "Process Injection", "properties": ['T1055', 'process (?:inject|inject[\\w]+)', 'LD_LIBRARY_PATH', 'DYLD_INSERT_LIBRARIES'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1012", "name": "Query Registry", "properties": ['T1012'], "stem": ['(?:quer[\\w]+|from) (?:the |)registr[\\w]+'], "keyword": ['registr[\\w]+', 'hkey_local_machin', 'hklm', 'hkey_current_config', 'hkcc', 'hkey_current_root', 'hkcr', 'hkey_us', 'hku', 'hkey_current_us', 'hkcu', 'hkey_performance_data', 'hkey_dyn_data'], "support": ['quer[\\w]+', 'communcat[\\w]+', 'pull', 'questio[\\w]+', 'interog[\\w]+', 'ask|asks', 'enumerat[\\w]+', 'check|checks', 'read|reads']},
  {"ID": "T1163", "name": "Rc.common", "properties": ['T1163', 'rc\\.common'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1164", "name": "Re-opened Applications", "properties": ['T1164', 'com\\.apple\\.loginwindow\\.plist', 'com\\.apple\\.loginwindow\\.\\*\\.plist'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1108", "name": "Redundant Access", "properties": ['T1108'], "stem": ['(?:multiple|additional|extra) (?:RAT(?:s|)|remote access|backdoors)', 'redundant access'], "keyword": [], "support": []},
  {"ID": "T1060", "name": "Registry Run Keys / Startup Folder", "properties": ['T1060', 'HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Run', 'HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce', 'HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Run', 'HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce', 'HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\RunOnceEx', 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnceEx\\0001\\Depend', 'HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\User', 'HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Shell', 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Shell', 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\User'], "stem": ['Registry Run Key(?:s|)', 'start(?:| )up (?:folder(?:s|)|director[\\w]+)', 'autostart extensibility point(?:s|)', '(?:adds |add |make |)(?:a |the |)run key (?:persistence |)(?:entry|entries)'], "keyword": ['(?:run key|startup)'], "support": ['registry']},
  {"ID": "T1121", "name": "Regsvcs/Regasm", "properties": ['T1121', 'Regsvcs', 'Regasm', 'ComRegisterFunction', 'ComUnregisterFunction'], "stem": ['Regsvcs(?:/| |)Regasm'], "keyword": [], "support": []},
  {"ID": "T1117", "name": "Regsvr32", "properties": ['T1117', 'Regsvr32\\.exe', 'Regsvr32'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1219", "name": "Remote Access Tools", "properties": ['T1219', 'RAT', 'Go2Assist', 'LogMein', 'AmmyyAdmin', 'VNC', 'Ammy', 'Teamviewer', 'LogMeIn'], "stem": ['remot[\\w]+ access (?:tool(?:s|)|trojan(?:s|))'], "keyword": [], "support": []},
  {"ID": "T1105", "name": "Remote File Copy", "properties": ['T1105', 'FTP', 'scp', 'rsync', 'sftp', 'dropper'], "stem": ['(?:downloa[\\w]+) (?:additional|subsequent|another|extra|)(?:file|files|script|scripts|tool|tools|software|softwares|componen[\\w]+|payloa[\\w]+)', '(?:copies |)remote file (?:transmission|copy)'], "keyword": [], "support": []},
  {"ID": "T1021", "name": "Remote Services", "properties": ['T1021', 'telnet', 'SSH', 'VNC', 'Putty'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1018", "name": "Remote System Discovery", "properties": ['T1018', 'ping', 'traceroute'], "stem": ['net view', 'remote (?:system |systems |)discovery'], "keyword": [], "support": []},
  {"ID": "T1496", "name": "Resource Hijacking", "properties": ["T1496", "resource (?:hijack|hijack[\\w]+)", "(?:hijack|hijack[\\w]+) resource "], "stem": ["cryptomin[\\w]+|crypto(?:-| |)min[\\w]+"], "keyword": [], "support": []},
  {"ID": "T1091", "name": "Replication Through Removable Media", "properties": ['T1091'], "stem": ['(?:replicat[\\w]+|infec[\\w]+)(?: through|) (?:removable media|USB(?:s|)|CD(?:s|))'], "keyword": ['infec[\\w]+|replicat[\\w]+|(?:copy|copies)|(?:spread(?:s|)|spreading)'], "support": ['removable media|USB(?:s|)|CD(?:s|)']},
  {"ID": "T1085", "name": "Rundll32", "properties": ['T1085', 'rundll32(?:\\.exe|)', 'Control_RunDLL', 'Control_RunDLLAsUser'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1494", "name": "Runtime Data Manipulation", "properties": ["T1494", "runtime data manipulation"], "stem": ["(?:manipulat[\\w]+)\\W+(?:\\w+\\W+){0,2}?(?:data)\\W+(?:\\w+\\W+){0,4}?(?:acces[\\w]+|displa[\\w]+|real(?:| )time)"], "keyword": [], "support": []},
  {"ID": "T1489", "name": "Service Stop", "properties": ["T1489", "service stop"], "stem": ["(?:disabl[\\w]+|stop|stop[\\w]+)\\W+(?:\\w+\\W+){0,3}service(?:|s)"], "keyword": [], "support": []},
  {"ID": "T1178", "name": "SID-History Injection", "properties": ['T1178','SID(?:-| |)History'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1198", "name": "SIP and Trust Provider Hijacking", "properties": ['T1198', 'SIPs', 'SIP', 'SIP_GUID', 'CryptSIPDllGetSignedDataMsg'], "stem": ['SIP(?:s|) and Trust Provider(?:s|) (?:Hijack|Hijacking)'], "keyword": [], "support": []},
  {"ID": "T1184", "name": "SSH Hijacking", "properties": ['T1184', 'SSHjack'], "stem": ['ssh(?: |-)(?:hijack|hijack[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1053", "name": "Scheduled Task", "properties": ['T1053', 'schtasks'], "stem": ['(?:schedul[\\w]+|automat[\\w]+)(?: a| the|) (?:task|tasks|execut[\\w]+|servic[\\w]+|tool|tools)', 'task schedul[\\w]+'], "keyword": [], "support": []},
  {"ID": "T1029", "name": "Scheduled Transfer", "properties": ['T1029'], "stem": ['(?:exfiltrat[\\w]+ |)schedul[\\w]+ transf[\\w]+'], "keyword": ['exfiltr[\\w]+', 'transfe[\\w]+', 'post|post[\\w]+', 'beacon|beacon[\\w]+', 'transmit[\\w]+'], "support": ['schedul[\\w]+', 'interv[\\w]+', 'hardcod[\\w]+', 'preset', 'rythmic', 'routin[\\w]+', 'regula[\\w]+']},
  {"ID": "T1113", "name": "Screen Capture", "properties": ['T1113', 'screen(?:| )captur[\\w]+', 'xwd'], "stem": [], "keyword": ['screenshot|screenshots|screen|screen[\\w]+', 'desktop|desktop[\\w]+'], "support": ['captur[\\w]+', 'collect|collect[\\w]+', 'grab|grab[\\w]+', 'seiz[\\w]+', 'record|record[\\w]+', 'take|taking']},
  {"ID": "T1180", "name": "Screensaver", "properties": ['T1180', 'scrnsave(?:\\.exe|)', 'screenSave[\\w]+', 'screensaver|screen saver'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1064", "name": "Scripting", "properties": ['T1064', '(?:batch |\\.bat |Java|)(?:script|script[\\w]+)', 'VBScript', 'VB(?:S|E|A)', 'macro|macros', '(?:[a-z0-9]+|)\\.(?:py|vbs|ps1|bat)'], "stem": ['(?:BAT|batch|\\.bat) (?:.*|)(?:file|files|script(?:s|))'], "keyword": [], "support": []},
  {"ID": "T1063", "name": "Security Software Discovery", "properties": ['T1063', 'netsh', 'dir', 'Tasklist', 'LittleSnitch', 'KnockKnock'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1101", "name": "Security Support Provider", "properties": ['T1101', 'SSP'], "stem": ['(?:windows |window\'s |)security support provider'], "keyword": [], "support": []},
  {"ID": "T1167", "name": "Securityd Memory", "properties": ['T1167', 'securityd'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1035", "name": "Service Execution", "properties": ['T1035'], "stem": ['(?:start(?:s|ing|)|execut[\\w]+|instal[\\w]+||creat[\\w]+|registe[\\w]+)(?: new|)(?: a|) servic[\\w]+', 'execut[\\w]+.*servic'], "keyword": [], "support": []},
  {"ID": "T1058", "name": "Service Registry Permissions Weakness", "properties": ['T1058', 'HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Services', 'sc\\.exe'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1166", "name": "Setuid and Setgid", "properties": ['T1166', 'setuid', 'setsuid', 'setgrid'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1051", "name": "Shared Webroot", "properties": ['T1051', 'webroot|webroots'], "stem": ['web content director[\\w]+'], "keyword": [], "support": []},
  {"ID": "T1023", "name": "Shortcut Modification", "properties": ['T1023', 'LNK|\\.lnk|[\\w]+\\.lnk'], "stem": ['(?:shortcut|symbolic lin[\\w]+) modifi[\\w]+', 'modifi[\\w]+ (?:shortcu[\\w]+|symbolic lin[\\w]+)'], "keyword": ['shortcut|LNK|\\.lnk|[\\w]+\\.lnk'], "support": ['replac[\\w]+|creat[\\w]+|manipulat[\\w]+|add(?:s|)']},
  {"ID": "T1218", "name": "Signed Binary Proxy Execution", "properties": ['T1218', 'Mavinject[\\w]+', 'shared\\\\ClickToRun\\\\MavInject32\\.exe', 'SyncAppvPublishingServer\\.exe', 'SyncAppvPublishingServer'], "stem": ['signed binary proxy execution'], "keyword": ['execut[\\w]+'], "support": ['binar[\\w]+ signed|signed binar[\\w]+']},
  {"ID": "T1216", "name": "Signed Script Proxy Execution", "properties": ['T1216', 'PubPrn', 'PubPrn\\.vbs'], "stem": ['signed script proxy execution', 'scrip[\\w]+|code|software signed', 'signed scrip[\\w]+|code|software'], "keyword": [], "support": []},
  {"ID": "T1045", "name": "Software Packing", "properties": ['T1045', '[\\w]+compression[\\w]+', 'packer(?:|s)', 'pack(?:s|)', 'MPRESS', 'UPX'], "stem": ['software packing'], "keyword": [], "support": []},
  {"ID": "T1153", "name": "Source", "properties": ['T1153'], "stem": ['source command', 'command source'], "keyword": [], "support": []},
  {"ID": "T1151", "name": "Space after Filename", "properties": ['T1151'], "stem": ['(?:appen[\\w]+|put|puts|place|places).*(?:space|blank character|white space|whitespace).*(?:file|filename|\\.jpeg|\\.txt|\\.doc|\\.rtf)'], "keyword": [], "support": []},
  {"ID": "T1193", "name": "Spearphishing Attachment", "properties": ['T1193'], "stem": ['(?:spearphish|spearphish[\\w]+|spear phis[\\w]+) attach[\\w]+'], "keyword": ['(?:spearphish|spearphish[\\w]+|spear phish|spear phish[\\w]+)'], "support": ['document|documents', 'file|files', 'vba|vbascript|vbs|vbscript']},
  {"ID": "T1192", "name": "Spearphishing Link", "properties": ['T1192'], "stem": [], "keyword": ['(?:spearphish|spearphish[\\w]+|spear phish|spear phish[\\w]+)'], "support": ['link|links', 'url', 'website|websites']},
  {"ID": "T1194", "name": "Spearphishing via Service", "properties": ['T1194'], "stem": ['(?:spearphish|spearphish[\\w]+|spear phish|spear phish[\\w]+) via servic[\\w]+'], "keyword": ['(?:spearphish|spearphish[\\w]+|spear phish|spear phish[\\w]+)'], "support": ['servic[\\w]+', 'facebook|facebook[\\w]+', 'instagram|instagram[\\w]+', 'twitter|twitter[\\w]+', 'whatsapp|whatsapp[\\w]+', 'media']},
  {"ID": "T1071", "name": "Standard Application Layer Protocol", "properties": ['T1071'], "stem": [], "keyword": ['command and control|C2|C&C'], "support": ['HTTP(?:S|\\\\S|)', 'SSH', 'TSL\\\\SSH', 'SMTP', 'DNS', 'RDP', 'port(?:| |-)(?:80|8080|22|(?:8|)443|3389|(?:25|465|587)|53)', 'Telnet', '(?:Trivial |)File Tranfer Protocol', '(?:T|)FTP', 'Simple Mail Transfer Protocol', 'Domain Name System', 'BOOTP', 'Simple Network Management Protocol', 'Common Management Information Protocol']},
  {"ID": "T1032", "name": "Standard Cryptographic Protocol", "properties": ['T1032', 'encryp[\\w]+', '(?:3|)DES', 'AES(?:-CBC|)', 'RSA', 'RC4', 'cipher', 'RC2'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1095", "name": "Standard Non-Application Layer Protocol", "properties": ['T1095', 'ICMP', 'UDP', '(?:raw |)socke[\\w]+', 'SOCKS', 'SOCKS5'], "stem": ['Internet Control Message Protocol', 'transport layer protoco[\\w]+', 'User datagram protocol', 'socket secure', 'serial over LAN'], "keyword": [], "support": []},
  {"ID": "T1165", "name": "Startup Items", "properties": ['T1165', 'Startup|startup[\\w]+', 'StartupParameters\\.plist', 'StartupItems'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1492", "name": "Stored Data Manipulation", "properties": ["T1492", "stored data manipulat[\\w]+"], "stem": ["(?:inser[\\w]+|delet[\\w]+|manipul[\\w]+) (?:stored|)\\W+(?:\\w+\\W+){0,2}?(?:data|file(?:|s)|record(?:|s))"], "keyword": [], "support": []},
  {"ID": "T1169", "name": "Sudo", "properties": ['T1169', 'sudoers', 'sudo'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1206", "name": "Sudo Caching", "properties": ['T1206', '/var/db/sudo', 'timestamp_timeout', 'tty_tickets'], "stem": ['sudo cache', 'sudo cached'], "keyword": [], "support": []},
  {"ID": "T1195", "name": "Supply Chain Compromise", "properties": ['T1195'], "stem": ['supply chain compromise', '(?:compromis[\\w]+|targe[\\w]+).*supply chain'], "keyword": [], "support": []},
  {"ID": "T1019", "name": "System Firmware", "properties": ['T1019'], "stem": ['UEFI Rootkit'], "keyword": ['modif[\\w]+|chang[\\w]+'], "support": ['BIOS|Basic Input(?: |/)Output Syste[\\w]+|Unified Extensible Firmware Inferface|UEFI|Extensible Firmware Interface|EFI']},
  {"ID": "T1082", "name": "System Information Discovery", "properties": ['T1082', 'systeminfo', 'dir', 'systemsetup', 'system_profiler', 'ver'], "stem": [], "keyword": ['(?:obtain|obtain[\\w]+|collec[\\w]+|gathe[\\w]+|determin[\\w]+|check|check[\\w]+|identif[\\w]+|enumerat[\\w]+|extrac[\\w]+)'], "support": ['(?:OS|operating syste\\w]+|Window[\\w]+|Window\'s) (?:versio[\\w]+|informat[\\w]+)', 'about the OS', 'local system', 'computer name|BIOS model|hostnam[\\w]+|host nam[\\w]+', 'disk (?:free|) space', 'processor', 'window resolution']},
  {"ID": "T1016", "name": "System Network Configuration Discovery", "properties": ['T1016', 'ARP', 'ipconfig', 'ifconfig', 'nbtstat'], "stem": ['system network configuratio[\\w]+ discove[\\w]+', '(?:obtain|obtain[\\w]+|collec[\\w]+|gathe[\\w]+|determin[\\w]+|check|check[\\w]+|identif[\\w]+|enumerat[\\w]+|extrac[\\w]+)\\W+(?:\\w+\\W+){0,6}?(?:IP|IPs|MAC|ARP|SSID|SSID[\\w]+|(?:network|domain|subnet|DHCP) (?:adapter |adapters |)(?:information|data|configuratio[\\w]+|config|configs))'], "keyword": [], "support": []},
  {"ID": "T1049", "name": "System Network Connections Discovery", "properties": ['T1049', 'netstat', 'nbtstat(?:\\.exe|)'], "stem": ['net use', 'net session', 'lsof', 'who -a', '(?:obtain|obtain[\\w]+|collec[\\w]+|gathe[\\w]+|determin[\\w]+|check|check[\\w]+|identif[\\w]+|enumerat[\\w]+|display)\\W+(?:\\w+\\W+){0,6}?(?:(?:network|TCP|active|current) connectio[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1033", "name": "System Owner/User Discovery", "properties": ['T1033', 'whoami'], "stem": ['query user', 'system (?:owner(?:|s(?:|/)| |/)|user|owner(?:|s(?:|/)| |/)user) discove[\\w]+', 'system (?:owner|user) discove[\\w]+', '(?:obtain|obtain[\\w]+|collec[\\w]+|gathe[\\w]+|determin[\\w]+|check|check[\\w]+|identif[\\w]+|enumerat[\\w]+)\\W+(?:\\w+\\W+){0,2}?(?:user|users|usernam[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1007", "name": "System Service Discovery", "properties": ['T1007', 'Tasklist'], "stem": ['net start', 'system service discovery', 'service discovery', '(?:data|informat[\\w]+|list)(?: from| on| the|)(?: available| running|) (?:program|programs|service|services)'], "keyword": ['(?:running|live|current|available|all) (?:services|service|tasks|task|programs|program)'], "support": ['(?:obtain|obtain[\\w]+|collec[\\w]+|gathe[\\w]+|determin[\\w]+|check|check[\\w]+|discover|discovers)']},
  {"ID": "T1124", "name": "System Time Discovery", "properties": ['T1124', 'w32tm', 'W32Time'], "stem": ['net time', 'system time discove[\\w]+', '(?:obtain|obtain[\\w]+|collec[\\w]+|gathe[\\w]+|determin[\\w]+|check|check[\\w]+)\\W+(?:\\w+\\W+){0,2}?(time|date)'], "keyword": [], "support": []},
  {"ID": "T1501", "name": "T1501", "properties": ["T1501", "Systemd (?:|Service)", "systemctl"], "stem": [], "keyword": [], "support": []},
  {"ID": "T1080", "name": "Taint Shared Content", "properties": ['T1080'], "stem": ['(?:taint|tainted) (?:share|shared) (?:content|contents)', '(?:share|shared) (?:taint|tainted) (?:content|contents)'], "keyword": ['(?:network|mapped|) (?:shared|share|shares)'], "support": ['(?:copy|copies) (?:itself|)', 'infect|infect[\\w]+']},
  {"ID": "T1221", "name": "Template Injection", "properties": ['T1221', 'OOXML'], "stem": ['(?:microsof[\w]+|microsoft\'s) open office XML', 'template referenc[\\w]+ (?:inject|inject[\\w]+)', 'template (?:inject|inject[\\w]+)', ], "keyword": ['template'], "support": ['inject|inject[\\w]+']},
  {"ID": "T1072", "name": "Third-party Software", "properties": ['T1072', 'SCCM', 'VNC', 'HBSS', 'Altiris'], "stem": ['third(?: |-)party (?:softwar[\\w]+|applicatio[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1209", "name": "Time Providers", "properties": ['T1209', 'W32Time', 'HKEY_LOCAL_MACHINE\\\\System\\\\CurrentControlSet\\\\Services\\\\W32Time\\\\TimeProviders\\\\'], "stem": ['time provide[\\w]+'], "keyword": [], "support": []},
  {"ID": "T1099", "name": "Timestomp", "properties": ['T1099', 'Timestomping'], "stem": [], "keyword": ['timestam[\\w]+|time stamp|time stamps|file creation (?:time|date)'], "support": ['modif[\\w]+|chang[\\w]+|backdate[\\w]+|fake|faked']},
  {"ID": "T1493", "name": "Transmitted Data Manipulation", "properties": ["T1493", "transmitted data manipulation", "manipul[\\w]+ transmi[\\w]+ data"], "stem": ["(?:manipul[\\w]+|chang[\\w]+|alter(?:|[\\w]+)) (?:data|message(?:|s)|email(?:|s)) (?:in transit|en route)"], "keyword": [], "support": []},
  {"ID": "T1154", "name": "Trap", "properties": ['T1154'], "stem": ['(?:execut[\\w]+).*interrup[\\w]+', 'interrup[\\w]+.*execut[\\w]+'], "keyword": ['trap'], "support": ['command']},
  {"ID": "T1127", "name": "Trusted Developer Utilities", "properties": ['T1127', 'MSBuild', 'MSBuild\\.exe', 'DNX\\.exe', 'DNX', 'RCSI', 'rcsi\\.exe', 'WinDbg', 'WinDbg\\.exe', 'cbd\\.exe', 'tracker\\.exe'], "stem": ['Microsoft Console Debugger', '(?:NET|\\.NET) Execution Environmen[\\w]+', 'Roslyn (?:NET|\\.NET) Complier Platform'], "keyword": ['(?:NET|\\.NET)'], "support": ['tracker']},
  {"ID": "T1199", "name": "Trusted Relationship", "properties": ['T1199'], "stem": ['trusted relationshi[\\w]+', 'third(?: |-)party', 'managed service provide[\\w]+|MSP(?:|(?:|\')s)'], "keyword": [], "support": []},
  {"ID": "T1111", "name": "Two-Factor Authentication Interception", "properties": ['T1111'], "stem": ['two(?: |-)factor (?:authent[\\w]+|)interceptio[\\w]+'], "keyword": ['(?:two-factor|two factor)', '2FA', 'multifactor'], "support": ['interceptio[\\w]+']},
  {"ID": "T1065", "name": "Uncommonly Used Port", "properties": ['T1065'], "stem": ['(?:port|tcp|udp)(?:| )(?!21|22|25|26|53|80|110|443|3389|8080|8443)[0-9]+'], "keyword": ['port|ports', 'communicat[\\w]+', 'tcp|udp'], "support": ['(?!21|22|25|26|53|80|110|443|3389|8080|8443)[0-9]+']},
  {"ID": "T1204", "name": "User Execution", "properties": ['T1204', 'Spearphis[\\w]+|spear phis[\\w]+', 'T1192'], "stem": ['(?:user|user[\\w]+|victi[\\w]+|owne[\\w]+)\\W+(?:\\w+\\W+){0,2}?(?:execut[\\w]+|open|open[\\w]+|click|click[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1078", "name": "Valid Accounts", "properties": ['T1078'], "stem": ['(?:compromis[\\w]+|stolen) credentia[\\w]+', 'valid accoun[\\w]+'], "keyword": ['credentia[\\w]+'], "support": ['legitimate', 'valid']},
  {"ID": "T1125", "name": "Video Capture", "properties": ['T1125', 'webcam(?:|s)'], "stem": ['captur[\\w]+|recor[\\w]+|access\\W+(?:\\w+\\W+){0,6}?(?:webcam|webcams|camer[\\w]+|vide[\\w]+|pictur[\\w]+)'], "keyword": [], "support": []},
  {"ID": "T1497", "name": "Virtualization/Sandbox Evasion", "properties": ["T1497", "(?:virtualization|sandbox) evasion"], "stem": ["(?:check(?:|s)|detect(?:|[\\w]+)|avoid(?:|[\\w]+|determin[\\w]+))\\W+(?:\\w+\\W+){0,4}?(?:virtual(?:|[\\w]+)|sandbox(?:|[\\w]+))(?: machine(?:|s)| analysis|) (?:environmen[\\w]+|software(?:|s)|machine(?:|s))", "(?:check(?:|s)|detect(?:|[\\w]+)|avoid(?:|[\\w]+|determin[\\w]+))\\W+(?:\\w+\\W+){0,4}?(?:VMWare|XEN|VirtualBox|QEmu|Virtual PC|Sandboxie)", "anti(?: |-)(?:VM|virual machin[\\w]+|sandbox)"], "keyword": [], "support": []},
  {"ID": "T1102", "name": "Web Service", "properties": ['T1102'], "stem": ['dead drop resolver'], "keyword": ['command and control|C2|C&C'], "support": ['web service', 'social (?:media|networ[\\w]+)', 'Google', 'Twitter', 'Dropbox', 'Mediafire', 'Yandex', 'RSS (?:feed|feeds)', 'Github', 'onedrive', 'tumbler', 'WordPress', 'forum|forums|blog|blogs']},
  {"ID": "T1100", "name": "Web Shell", "properties": ['T1100'], "stem": ['(?:web|web[\\w]+) (?:shell[\\w]+|shell)'], "keyword": [], "support": []},
  {"ID": "T1077", "name": "Windows Admin Shares", "properties": ['T1077', 'SMB', 'RPCs'], "stem": ['remote procedure (?:call|calls)', 'C$', 'ADMIN$', 'IPC$', '(?:admin|adminstrat[\\w]+) (?:share|shares)'], "keyword": ['(?:network|mapped) shares'], "support": ['admin|adminstrat[\\w]+']},
  {"ID": "T1047", "name": "Windows Management Instrumentation", "properties": ['T1047'], "stem": ['WMI|Windows Management Instrumentation', '^(?!.*persistence|.*event).*WMI.*$'], "keyword": [], "support": []},
  {"ID": "T1084", "name": "Windows Management Instrumentation Event Subscription", "properties": ['T1084'], "stem": ['Windows Management Instrumentation Event Subscriptio[\\w]+'], "keyword": ['WMI|Windows Management Instrumentation'], "support": ['event|events', 'script|scripts', 'persistence']},
  {"ID": "T1004", "name": "Winlogon Helper DLL", "properties": ['T1004', 'Winlogon\\.exe', 'NT\\\\CurrentVersion\\\\Winlogon\\\\', 'Winlogon', 'Winlogon\\\\Notify', 'Winlogon\\\\Userinit', 'Winlogon\\\\Shell'], "stem": [], "keyword": [], "support": []},
  {"ID": "T1220", "name": "XSL Script Processing", "properties": ['T1220', 'msxsl\\.exe', 'MSXSL', '\\.xsl', 'XSL'], "stem": ['extensibile stylesheet language'], "keyword": [], "support": []}
]

entityList = [
/*Malware*/
  {"ID": "3PARA RAT", "entity": "Malware", "aliases": ["3PARA RAT"]},
  {"ID": "4H RAT", "entity": "Malware", "aliases": ["4H RAT"]},
  {"ID": "ADVSTORESHELL", "entity": "Malware", "aliases": ["ADVSTORESHELL", "AZZY", "EVILTOSS", "NETUI", "Sedreco"]},
  {"ID": "ASPXSpy", "entity": "Malware", "aliases": ["ASPXSpy", "ASPXTool"]},
  {"ID": "Agent.btz", "entity": "Malware", "aliases": ["Agent\\.btz"]},
  {"ID": "AutoIt backdoor", "entity": "Malware", "aliases": ["AutoIt backdoor"]},
  {"ID": "BACKSPACE", "entity": "Malware", "aliases": ["BACKSPACE", "Lecna"]},
  {"ID": "BADCALL", "entity": "Malware", "aliases": ["BADCALL"]},
  {"ID": "BADNEWS", "entity": "Malware", "aliases": ["BADNEWS"]},
  {"ID": "BBSRAT", "entity": "Malware", "aliases": ["BBSRAT"]},
  {"ID": "BISCUIT", "entity": "Malware", "aliases": ["BISCUIT"]},
  {"ID": "BLACKCOFFEE", "entity": "Malware", "aliases": ["BLACKCOFFEE"]},
  {"ID": "BOOTRASH", "entity": "Malware", "aliases": ["BOOTRASH"]},
  {"ID": "BS2005", "entity": "Malware", "aliases": ["BS2005"]},
  {"ID": "BUBBLEWRAP", "entity": "Malware", "aliases": ["BUBBLEWRAP", "Backdoor\\.APT\\.FakeWinHTTPHelper"]},
  {"ID": "Backdoor.Oldrea", "entity": "Malware", "aliases": ["Backdoor\\.Oldrea", "Havex"]},
  {"ID": "Bandook", "entity": "Malware", "aliases": ["Bandook"]},
  {"ID": "Bankshot", "entity": "Malware", "aliases": ["Bankshot", "Trojan Manuscript"]},
  {"ID": "Bisonal", "entity": "Malware", "aliases": ["Bisonal"]},
  {"ID": "BlackEnergy", "entity": "Malware", "aliases": ["BlackEnergy", "Black Energy"]},
  {"ID": "Brave Prince", "entity": "Malware", "aliases": ["Brave Prince"]},
  {"ID": "Briba", "entity": "Malware", "aliases": ["Briba"]},
  {"ID": "CALENDAR", "entity": "Malware", "aliases": ["CALENDAR"]},
  {"ID": "CCBkdr", "entity": "Malware", "aliases": ["CCBkdr"]},
  {"ID": "CHOPSTICK", "entity": "Malware", "aliases": ["CHOPSTICK", "SPLM", "Xagent", "X-Agent", "webhp"]},
  {"ID": "CORALDECK", "entity": "Malware", "aliases": ["CORALDECK"]},
  {"ID": "CORESHELL", "entity": "Malware", "aliases": ["CORESHELL", "SOURFACE"]},
  {"ID": "Calisto", "entity": "Malware", "aliases": ["Calisto"]},
  {"ID": "CallMe", "entity": "Malware", "aliases": ["CallMe"]},
  {"ID": "Carbanak", "entity": "Malware", "aliases": ["Carbanak", "Anunak"]},
  {"ID": "Catchamas", "entity": "Malware", "aliases": ["Catchamas"]},
  {"ID": "ChChes", "entity": "Malware", "aliases": ["ChChes", "Scorpion", "HAYMAKER"]},
  {"ID": "Chaos", "entity": "Malware", "aliases": ["Chaos"]},
  {"ID": "Cherry Picker", "entity": "Malware", "aliases": ["Cherry Picker"]},
  {"ID": "China Chopper", "entity": "Malware", "aliases": ["China Chopper"]},
  {"ID": "CloudDuke", "entity": "Malware", "aliases": ["CloudDuke", "MiniDionis", "CloudLook"]},
  {"ID": "ComRAT", "entity": "Malware", "aliases": ["ComRAT"]},
  {"ID": "Comnie", "entity": "Malware", "aliases": ["Comnie"]},
  {"ID": "CosmicDuke", "entity": "Malware", "aliases": ["CosmicDuke", "TinyBaron", "BotgenStudios", "NemesisGemina"]},
  {"ID": "CozyCar", "entity": "Malware", "aliases": ["CozyCar", "CozyDuke", "CozyBear", "Cozer", "EuroAPT"]},
  {"ID": "Crimson", "entity": "Malware", "aliases": ["Crimson", "MSIL/Crimson"]},
  {"ID": "CrossRAT", "entity": "Malware", "aliases": ["CrossRAT"]},
  {"ID": "DDKONG", "entity": "Malware", "aliases": ["DDKONG"]},
  {"ID": "DOGCALL", "entity": "Malware", "aliases": ["DOGCALL"]},
  {"ID": "Darkmoon", "entity": "Malware", "aliases": []},
  {"ID": "Daserf", "entity": "Malware", "aliases": ["Daserf", "Muirim", "Nioupale"]},
  {"ID": "DealersChoice", "entity": "Malware", "aliases": ["DealersChoice"]},
  {"ID": "Derusbi", "entity": "Malware", "aliases": ["Derusbi", "PHOTO"]},
  {"ID": "Dipsind", "entity": "Malware", "aliases": ["Dipsind"]},
  {"ID": "Dok", "entity": "Malware", "aliases": ["Dok", "Retefe"]},
  {"ID": "DownPaper", "entity": "Malware", "aliases": ["DownPaper"]},
  {"ID": "Downdelph", "entity": "Malware", "aliases": ["Downdelph", "Delphacy"]},
  {"ID": "Duqu", "entity": "Malware", "aliases": ["Duqu"]},
  {"ID": "DustySky", "entity": "Malware", "aliases": ["DustySky", "NeD Worm"]},
  {"ID": "Dyre", "entity": "Malware", "aliases": ["Dyre"]},
  {"ID": "ELMER", "entity": "Malware", "aliases": ["ELMER"]},
  {"ID": "Elise", "entity": "Malware", "aliases": ["Elise", "BKDR_ESILE"]},
  {"ID": "Emissary", "entity": "Malware", "aliases": ["Emissary"]},
  {"ID": "Epic", "entity": "Malware", "aliases": ["Epic", "Tavdig", "Wipbot", "WorldCupSec", "TadjMakhal"]},
  {"ID": "EvilGrab", "entity": "Malware", "aliases": ["EvilGrab"]},
  {"ID": "FALLCHILL", "entity": "Malware", "aliases": ["FALLCHILL"]},
  {"ID": "FELIXROOT", "entity": "Malware", "aliases": ["FELIXROOT"]},
  {"ID": "FLASHFLOOD", "entity": "Malware", "aliases": ["FLASHFLOOD"]},
  {"ID": "FLIPSIDE", "entity": "Malware", "aliases": ["FLIPSIDE"]},
  {"ID": "FakeM", "entity": "Malware", "aliases": ["FakeM"]},
  {"ID": "Felismus", "entity": "Malware", "aliases": ["Felismus"]},
  {"ID": "FinFisher", "entity": "Malware", "aliases": ["FinFisher", "FinSpy"]},
  {"ID": "Flame", "entity": "Malware", "aliases": ["Flame", "Flamer", "sKyWIper"]},
  {"ID": "FruitFly", "entity": "Malware", "aliases": ["FruitFly"]},
  {"ID": "GLOOXMAIL", "entity": "Malware", "aliases": ["GLOOXMAIL", "Trojan\\.GTALK"]},
  {"ID": "Gazer", "entity": "Malware", "aliases": ["Gazer", "WhiteBear"]},
  {"ID": "GeminiDuke", "entity": "Malware", "aliases": ["GeminiDuke"]},
  {"ID": "Gold Dragon", "entity": "Malware", "aliases": ["Gold Dragon"]},
  {"ID": "GravityRAT", "entity": "Malware", "aliases": ["GravityRAT"]},
  {"ID": "H1N1", "entity": "Malware", "aliases": ["H1N1"]},
  {"ID": "HALFBAKED", "entity": "Malware", "aliases": ["HALFBAKED"]},
  {"ID": "HAMMERTOSS", "entity": "Malware", "aliases": ["HAMMERTOSS", "HammerDuke", "NetDuke"]},
  {"ID": "HAPPYWORK", "entity": "Malware", "aliases": ["HAPPYWORK"]},
  {"ID": "HARDRAIN", "entity": "Malware", "aliases": ["HARDRAIN"]},
  {"ID": "HDoor", "entity": "Malware", "aliases": ["HDoor", "Custom HDoor"]},
  {"ID": "HIDEDRV", "entity": "Malware", "aliases": ["HIDEDRV"]},
  {"ID": "HOMEFRY", "entity": "Malware", "aliases": ["HOMEFRY"]},
  {"ID": "HTTPBrowser", "entity": "Malware", "aliases": ["HTTPBrowser", "Token Control", "HttpDump"]},
  {"ID": "Hacking Team UEFI Rootkit", "entity": "Malware", "aliases": ["Hacking Team UEFI Rootkit"]},
  {"ID": "Helminth", "entity": "Malware", "aliases": ["Helminth"]},
  {"ID": "Hi-Zor", "entity": "Malware", "aliases": ["Hi-Zor"]},
  {"ID": "Hikit", "entity": "Malware", "aliases": ["Hikit"]},
  {"ID": "Hydraq", "entity": "Malware", "aliases": ["Hydraq", "Aurora", "9002 RAT"]},
  {"ID": "ISMInjector", "entity": "Malware", "aliases": ["ISMInjector"]},
  {"ID": "InnaputRAT", "entity": "Malware", "aliases": ["InnaputRAT"]},
  {"ID": "InvisiMole", "entity": "Malware", "aliases": ["InvisiMole"]},
  {"ID": "Ixeshe", "entity": "Malware", "aliases": ["Ixeshe"]},
  {"ID": "JHUHUGIT", "entity": "Malware", "aliases": ["JHUHUGIT", "Seduploader", "JKEYSKW", "Sednit", "GAMEFISH", "SofacyCarberp"]},
  {"ID": "JPIN", "entity": "Malware", "aliases": ["JPIN"]},
  {"ID": "Janicab", "entity": "Malware", "aliases": ["Janicab"]},
  {"ID": "KARAE", "entity": "Malware", "aliases": ["KARAE"]},
  {"ID": "KEYMARBLE", "entity": "Malware", "aliases": ["KEYMARBLE"]},
  {"ID": "KOMPROGO", "entity": "Malware", "aliases": ["KOMPROGO"]},
  {"ID": "Kasidet", "entity": "Malware", "aliases": ["Kasidet"]},
  {"ID": "Kazuar", "entity": "Malware", "aliases": ["Kazuar"]},
  {"ID": "Keydnap", "entity": "Malware", "aliases": ["Keydnap", "OSX/Keydnap"]},
  {"ID": "Komplex", "entity": "Malware", "aliases": ["Komplex"]},
  {"ID": "Kwampirs", "entity": "Malware", "aliases": ["Kwampirs"]},
  {"ID": "LOWBALL", "entity": "Malware", "aliases": ["LOWBALL"]},
  {"ID": "Linfo", "entity": "Malware", "aliases": ["Linfo"]},
  {"ID": "Lurid", "entity": "Malware", "aliases": ["Lurid", "Enfal"]},
  {"ID": "MURKYTOP", "entity": "Malware", "aliases": ["MURKYTOP"]},
  {"ID": "MacSpy", "entity": "Malware", "aliases": ["MacSpy"]},
  {"ID": "Matroyshka", "entity": "Malware", "aliases": ["Matroyshka"]},
  {"ID": "Miner-C", "entity": "Malware", "aliases": ["Miner-C", "Mal/Miner-C", "PhotoMiner"]},
  {"ID": "MiniDuke", "entity": "Malware", "aliases": ["MiniDuke"]},
  {"ID": "MirageFox", "entity": "Malware", "aliases": ["MirageFox"]},
  {"ID": "Mis-Type", "entity": "Malware", "aliases": ["Mis-Type"]},
  {"ID": "Misdat", "entity": "Malware", "aliases": ["Misdat"]},
  {"ID": "Mivast", "entity": "Malware", "aliases": ["Mivast"]},
  {"ID": "MobileOrder", "entity": "Malware", "aliases": ["MobileOrder"]},
  {"ID": "MoonWind", "entity": "Malware", "aliases": ["MoonWind"]},
  {"ID": "More_eggs", "entity": "Malware", "aliases": ["More_eggs"]},
  {"ID": "Mosquito", "entity": "Malware", "aliases": ["Mosquito"]},
  {"ID": "NDiskMonitor", "entity": "Malware", "aliases": ["NDiskMonitor"]},
  {"ID": "NETEAGLE", "entity": "Malware", "aliases": ["NETEAGLE"]},
  {"ID": "NETWIRE", "entity": "Malware", "aliases": ["NETWIRE"]},
  {"ID": "Naid", "entity": "Malware", "aliases": ["Naid"]},
  {"ID": "NanHaiShu", "entity": "Malware", "aliases": ["NanHaiShu"]},
  {"ID": "NavRAT", "entity": "Malware", "aliases": ["NavRAT"]},
  {"ID": "Nerex", "entity": "Malware", "aliases": ["Nerex"]},
  {"ID": "Net Crawler", "entity": "Malware", "aliases": ["Net(?:| )Crawler", "NetC"]},
  {"ID": "NetTraveler", "entity": "Malware", "aliases": ["NetTraveler"]},
  {"ID": "Nidiran", "entity": "Malware", "aliases": ["Nidiran", "Backdoor\\.Nidiran"]},
  {"ID": "OLDBAIT", "entity": "Malware", "aliases": ["OLDBAIT", "Sasfis"]},
  {"ID": "OSInfo", "entity": "Malware", "aliases": ["OSInfo"]},
  {"ID": "OnionDuke", "entity": "Malware", "aliases": ["OnionDuke"]},
  {"ID": "OopsIE", "entity": "Malware", "aliases": ["OopsIE"]},
  {"ID": "Orz", "entity": "Malware", "aliases": ["AIRBREAK", "Orz"]},
  {"ID": "OwaAuth", "entity": "Malware", "aliases": ["OwaAuth"]},
  {"ID": "P2P ZeuS", "entity": "Malware", "aliases": ["P2P ZeuS", "Peer(?:|-| )to(?:|-| )Peer ZeuS", "Gameover ZeuS"]},
  {"ID": "PHOREAL", "entity": "Malware", "aliases": ["PHOREAL"]},
  {"ID": "PLAINTEE", "entity": "Malware", "aliases": ["PLAINTEE"]},
  {"ID": "POORAIM", "entity": "Malware", "aliases": ["POORAIM"]},
  {"ID": "POSHSPY", "entity": "Malware", "aliases": ["POSHSPY"]},
  {"ID": "POWERSOURCE", "entity": "Malware", "aliases": ["POWERSOURCE", "DNSMessenger"]},
  {"ID": "POWERSTATS", "entity": "Malware", "aliases": ["POWERSTATS"]},
  {"ID": "POWRUNER", "entity": "Malware", "aliases": ["POWRUNER"]},
  {"ID": "PUNCHBUGGY", "entity": "Malware", "aliases": ["PUNCHBUGGY"]},
  {"ID": "PUNCHTRACK", "entity": "Malware", "aliases": ["PUNCHTRACK", "PSVC"]},
  {"ID": "Pasam", "entity": "Malware", "aliases": ["Pasam"]},
  {"ID": "PinchDuke", "entity": "Malware", "aliases": ["PinchDuke"]},
  {"ID": "Pisloader", "entity": "Malware", "aliases": ["Pisloader"]},
  {"ID": "PlugX", "entity": "Malware", "aliases": ["PlugX", "Sogu", "Kaba", "Korplug"]},
  {"ID": "PoisonIvy", "entity": "Malware", "aliases": ["Poison(?:| )Ivy", "Darkmoon"]},
  {"ID": "Power Loader", "entity": "Malware", "aliases": ["Power(?:| )Loader", "Win32/Agent\\.UAW"]},
  {"ID": "PowerDuke", "entity": "Malware", "aliases": ["PowerDuke"]},
  {"ID": "Prikormka", "entity": "Malware", "aliases": ["Prikormka"]},
  {"ID": "Proton", "entity": "Malware", "aliases": ["Proton"]},
  {"ID": "Proxysvc", "entity": "Malware", "aliases": ["Proxysvc"]},
  {"ID": "Psylo", "entity": "Malware", "aliases": ["Psylo"]},
  {"ID": "Pteranodon", "entity": "Malware", "aliases": ["Pteranodon"]},
  {"ID": "QUADAGENT", "entity": "Malware", "aliases": ["QUADAGENT"]},
  {"ID": "RARSTONE", "entity": "Malware", "aliases": ["RARSTONE"]},
  {"ID": "RATANKBA", "entity": "Malware", "aliases": ["RATANKBA"]},
  {"ID": "RGDoor", "entity": "Malware", "aliases": ["RGDoor"]},
  {"ID": "RIPTIDE", "entity": "Malware", "aliases": ["RIPTIDE"]},
  {"ID": "ROCKBOOT", "entity": "Malware", "aliases": ["ROCKBOOT"]},
  {"ID": "ROKRAT", "entity": "Malware", "aliases": ["ROKRAT"]},
  {"ID": "RTM", "entity": "Malware", "aliases": ["RTM"]},
  {"ID": "RawPOS", "entity": "Malware", "aliases": ["RawPOS", "FIENDCRY", "DUEBREW", "DRIFTWOOD"]},
  {"ID": "Reaver", "entity": "Malware", "aliases": ["Reaver"]},
  {"ID": "RedLeaves", "entity": "Malware", "aliases": ["RedLeaves", "BUGJUICE"]},
  {"ID": "Regin", "entity": "Malware", "aliases": ["Regin"]},
  {"ID": "RemoteCMD", "entity": "Malware", "aliases": ["RemoteCMD"]},
  {"ID": "Remsec", "entity": "Malware", "aliases": ["Remsec", "Backdoor\\.Remsec", "ProjectSauron"]},
  {"ID": "RogueRobin", "entity": "Malware", "aliases": ["RogueRobin"]},
  {"ID": "Rover", "entity": "Malware", "aliases": ["Rover"]},
  {"ID": "RunningRAT", "entity": "Malware", "aliases": ["RunningRAT"]},
  {"ID": "S-Type", "entity": "Malware", "aliases": ["S-Type"]},
  {"ID": "SEASHARPEE", "entity": "Malware", "aliases": ["SEASHARPEE"]},
  {"ID": "SHIPSHAPE", "entity": "Malware", "aliases": ["SHIPSHAPE"]},
  {"ID": "SHOTPUT", "entity": "Malware", "aliases": ["SHOTPUT", "(?:Backdoor\\.APT\\.|)CookieCutter", "Pirpi"]},
  {"ID": "SHUTTERSPEED", "entity": "Malware", "aliases": ["SHUTTERSPEED"]},
  {"ID": "SLOWDRIFT", "entity": "Malware", "aliases": ["SLOWDRIFT"]},
  {"ID": "SNUGRIDE", "entity": "Malware", "aliases": ["SNUGRIDE"]},
  {"ID": "SOUNDBITE", "entity": "Malware", "aliases": ["SOUNDBITE"]},
  {"ID": "SPACESHIP", "entity": "Malware", "aliases": ["SPACESHIP"]},
  {"ID": "Sakula", "entity": "Malware", "aliases": ["Sakula", "Sakurel", "VIPER"]},
  {"ID": "SeaDuke", "entity": "Malware", "aliases": ["SeaDuke", "SeaDaddy", "SeaDesk"]},
  {"ID": "Shamoon", "entity": "Malware", "aliases": ["Shamoon", "Disttrack"]},
  {"ID": "Skeleton Key", "entity": "Malware", "aliases": ["Skeleton Key"]},
  {"ID": "Smoke Loader", "entity": "Malware", "aliases": ["Smoke(?:| )Loader", "Dofoil"]},
  {"ID": "Socksbot", "entity": "Malware", "aliases": ["Socksbot"]},
  {"ID": "SslMM", "entity": "Malware", "aliases": ["SslMM"]},
  {"ID": "Starloader", "entity": "Malware", "aliases": ["Starloader"]},
  {"ID": "StreamEx", "entity": "Malware", "aliases": ["StreamEx"]},
  {"ID": "Sykipot", "entity": "Malware", "aliases": ["Sykipot"]},
  {"ID": "SynAck", "entity": "Malware", "aliases": ["SynAck"]},
  {"ID": "Sys10", "entity": "Malware", "aliases": ["Sys10"]},
  {"ID": "T9000", "entity": "Malware", "aliases": ["T9000"]},
  {"ID": "TDTESS", "entity": "Malware", "aliases": ["TDTESS"]},
  {"ID": "TEXTMATE", "entity": "Malware", "aliases": ["TEXTMATE", "DNSMessenger"]},
  {"ID": "TINYTYPHON", "entity": "Malware", "aliases": ["TINYTYPHON"]},
  {"ID": "TURNEDUP", "entity": "Malware", "aliases": ["TURNEDUP"]},
  {"ID": "TYPEFRAME", "entity": "Malware", "aliases": ["TYPEFRAME"]},
  {"ID": "Taidoor", "entity": "Malware", "aliases": ["Taidoor"]},
  {"ID": "TinyZBot", "entity": "Malware", "aliases": ["TinyZBot"]},
  {"ID": "TrickBot", "entity": "Malware", "aliases": ["TrickBot", "Totbrick", "TSPY_TRICKLOAD"]},
  {"ID": "Trojan.Karagany", "entity": "Malware", "aliases": ["Trojan\\.Karagany"]},
  {"ID": "Trojan.Mebromi", "entity": "Malware", "aliases": ["Trojan\\.Mebromi"]},
  {"ID": "Truvasys", "entity": "Malware", "aliases": ["Truvasys"]},
  {"ID": "UPPERCUT", "entity": "Malware", "aliases": ["UPPERCUT", "ANEL"]},
  {"ID": "USBStealer", "entity": "Malware", "aliases": ["USB(?:| )Stealer", "Win32/USBStealer"]},
  {"ID": "Umbreon", "entity": "Malware", "aliases": ["Umbreon"]},
  {"ID": "Unknown Logger", "entity": "Malware", "aliases": ["Unknown Logger"]},
  {"ID": "Uroburos", "entity": "Malware", "aliases": ["Uroburos"]},
  {"ID": "VERMIN", "entity": "Malware", "aliases": ["VERMIN"]},
  {"ID": "Vasport", "entity": "Malware", "aliases": ["Vasport"]},
  {"ID": "Volgmer", "entity": "Malware", "aliases": ["Volgmer"]},
  {"ID": "WEBC2", "entity": "Malware", "aliases": ["WEBC2"]},
  {"ID": "WINDSHIELD", "entity": "Malware", "aliases": ["WINDSHIELD"]},
  {"ID": "WINERACK", "entity": "Malware", "aliases": ["WINERACK"]},
  {"ID": "Wiarp", "entity": "Malware", "aliases": ["Wiarp"]},
  {"ID": "WinMM", "entity": "Malware", "aliases": ["WinMM"]},
  {"ID": "Wingbird", "entity": "Malware", "aliases": ["Wingbird"]},
  {"ID": "Winnti", "entity": "Malware", "aliases": ["Winnti"]},
  {"ID": "Wiper", "entity": "Malware", "aliases": ["Wiper"]},
  {"ID": "XAgentOSX", "entity": "Malware", "aliases": ["XAgentOSX"]},
  {"ID": "XTunnel", "entity": "Malware", "aliases": ["XTunnel", "X-Tunnel", "XAPS"]},
  {"ID": "ZLib", "entity": "Malware", "aliases": ["ZLib"]},
  {"ID": "Zebrocy", "entity": "Malware", "aliases": ["Zebrocy"]},
  {"ID": "ZeroT", "entity": "Malware", "aliases": ["ZeroT"]},
  {"ID": "Zeroaccess", "entity": "Malware", "aliases": ["Zeroaccess", "Trojan\\.Zeroaccess"]},
  {"ID": "adbupd", "entity": "Malware", "aliases": ["adbupd"]},
  {"ID": "gh0st", "entity": "Malware", "aliases": ["gh0st"]},
  {"ID": "hcdLoader", "entity": "Malware", "aliases": ["hcdLoader"]},
  {"ID": "httpclient", "entity": "Malware", "aliases": ["httpclient"]},
  {"ID": "iKitten", "entity": "Malware", "aliases": ["iKitten", "OSX/MacDownloader"]},
  {"ID": "jRAT", "entity": "Malware", "aliases": ["jRAT", "Trojan\\.Maljava"]},
  {"ID": "pngdowner", "entity": "Malware", "aliases": ["pngdowner"]},
  {"ID": "yty", "entity": "Malware", "aliases": ["yty"]},
/*Adversary group*/
  {"ID": "APT1", "entity": "Adversary", "aliases": ["APT(?:| )1", "Comment Crew", "Comment Group", "Comment Panda"]},
  {"ID": "APT12", "entity": "Adversary", "aliases": ["APT(?:| )12", "IXESHE", "DynCalc", "Numbered Panda", "DNSCALC"]},
  {"ID": "APT16", "entity": "Adversary", "aliases": ["APT(?:| )16"]},
  {"ID": "APT17", "entity": "Adversary", "aliases": ["APT(?:| )17", "Deputy Dog"]},
  {"ID": "APT18", "entity": "Adversary", "aliases": ["APT(?:| )18", "(?:TG|Threat Group)(?:-| |)0416", "Dynamite Panda"]},
  {"ID": "APT19", "entity": "Adversary", "aliases": ["APT(?:| )19", "Codoso", "C0d0so0", "Codoso Team", "Sunshop Group"]},
  {"ID": "APT28", "entity": "Adversary", "aliases": ["APT(?:| )28", "Sednit", "Sofacy", "Pawn Storm", "Fancy Bear", "STRONTIUM", "Tsar Team", "Threat Group-4127", "TG(?:-| |)4127"]},
  {"ID": "APT29", "entity": "Adversary", "aliases": ["APT(?:| )29", "The Dukes", "Cozy Bear", "CozyDuke"]},
  {"ID": "APT3", "entity": "Adversary", "aliases": ["APT(?:| )3", "Gothic(?:| )Panda", "Pirpi", "UPS Team", "Buckeye", "Threat Group-0110", "TG(?:-| |)0110"]},
  {"ID": "APT30", "entity": "Adversary", "aliases": ["APT(?:| )30"]},
  {"ID": "APT32", "entity": "Adversary", "aliases": ["APT(?:| )32", "Ocean(?:| )Lotus Group", "APT-C-00"]},
  {"ID": "APT33", "entity": "Adversary", "aliases": ["APT(?:| )33"]},
  {"ID": "APT34", "entity": "Adversary", "aliases": ["APT(?:| )34"]},
  {"ID": "APT37", "entity": "Adversary", "aliases": ["ScarCruft", "APT(?:| )37", "Reaper", "Group123", "TEMP\\.Reaper"]},
  {"ID": "Axiom", "entity": "Adversary", "aliases": ["Axiom", "Group 72"]},
  {"ID": "BRONZE BUTLER", "entity": "Adversary", "aliases": ["BRONZE BUTLER", "REDBALDKNIGHT", "Tick"]},
  {"ID": "BlackOasis", "entity": "Adversary", "aliases": ["BlackOasis"]},
  {"ID": "Carbanak", "entity": "Adversary", "aliases": ["Carbanak", "Anunak", "Carbon(?:| )Spider"]},
  {"ID": "Charming Kitten", "entity": "Adversary", "aliases": ["Charming(?:| )Kitten"]},
  {"ID": "Cleaver", "entity": "Adversary", "aliases": ["Cleaver", "Threat Group 2889", "TG(?:-| |)2889"]},
  {"ID": "Cobalt Group", "entity": "Adversary", "aliases": ["Cobalt (?:Group|Gang)", "Cobalt Spider"]},
  {"ID": "CopyKittens", "entity": "Adversary", "aliases": ["Copy(?:| )Kittens"]},
  {"ID": "Dark Caracal", "entity": "Adversary", "aliases": ["Dark Caracal"]},
  {"ID": "DarkHydrus", "entity": "Adversary", "aliases": ["DarkHydrus"]},
  {"ID": "Darkhotel", "entity": "Adversary", "aliases": ["Darkhotel"]},
  {"ID": "Deep Panda", "entity": "Adversary", "aliases": ["Deep P\anda", "Shell Crew", "WebMasters", "KungFu Kittens", "PinkPanther", "Black Vine"]},
  {"ID": "DragonOK", "entity": "Adversary", "aliases": ["DragonOK"]},
  {"ID": "Dragonfly", "entity": "Adversary", "aliases": ["Dragonfly", "Energetic Bear"]},
  {"ID": "Dragonfly 2.0", "entity": "Adversary", "aliases": ["Dragonfly 2\\.0", "Berserk Bear"]},
  {"ID": "Dust Storm", "entity": "Adversary", "aliases": ["Dust Storm"]},
  {"ID": "Elderwood", "entity": "Adversary", "aliases": ["Elderwood", "Elderwood Gang", "Beijing Group", "Sneaky Panda"]},
  {"ID": "Equation", "entity": "Adversary", "aliases": ["Equation"]},
  {"ID": "FIN10", "entity": "Adversary", "aliases": ["FIN(?:| )10"]},
  {"ID": "FIN5", "entity": "Adversary", "aliases": ["FIN(?:| )5"]},
  {"ID": "FIN6", "entity": "Adversary", "aliases": ["FIN(?:| )6"]},
  {"ID": "FIN7", "entity": "Adversary", "aliases": ["FIN(?:| )7"]},
  {"ID": "FIN8", "entity": "Adversary", "aliases": ["FIN(?:| )8"]},
  {"ID": "GCMAN", "entity": "Adversary", "aliases": ["GCMAN"]},
  {"ID": "Gamaredon Group", "entity": "Adversary", "aliases": ["Gamaredon Group"]},
  {"ID": "Gorgon Group", "entity": "Adversary", "aliases": ["Gorgon Group"]},
  {"ID": "Group5", "entity": "Adversary", "aliases": ["Group5"]},
  {"ID": "Honeybee", "entity": "Adversary", "aliases": ["Honeybee"]},
  {"ID": "Ke3chang", "entity": "Adversary", "aliases": ["Ke3chang", "APT15", "Mirage", "Vixen Panda", "GREF", "Playful Dragon", "RoyalAPT"]},
  {"ID": "Lazarus Group", "entity": "Adversary", "aliases": ["Lazarus Group", "HIDDEN COBRA", "Guardians of Peace", "ZINC", "NICKEL ACADEMY"]},
  {"ID": "Leafminer", "entity": "Adversary", "aliases": ["Leafminer"]},
  {"ID": "Leviathan", "entity": "Adversary", "aliases": ["Leviathan", "TEMP\\.Periscope"]},
  {"ID": "Lotus Blossom", "entity": "Adversary", "aliases": ["Lotus Blossom", "Spring Dragon"]},
  {"ID": "MONSOON", "entity": "Adversary", "aliases": ["Monsoon"]},
  {"ID": "Magic Hound", "entity": "Adversary", "aliases": ["Magic Hound", "Rocket Kitten", "Operation Saffron Rose", "Ajax Security Team", "Operation Woolen-Goldfish", "Newscaster", "Cobalt Gypsy", "APT35"]},
  {"ID": "Moafee", "entity": "Adversary", "aliases": ["Moafee"]},
  {"ID": "Molerats", "entity": "Adversary", "aliases": ["Molerats", "Operation Molerats", "Gaza Cybergang"]},
  {"ID": "MuddyWater", "entity": "Adversary", "aliases": ["MuddyWater", "TEMP\\.Zagros"]},
  {"ID": "NEODYMIUM", "entity": "Adversary", "aliases": ["NEODYMIUM"]},
  {"ID": "Naikon", "entity": "Adversary", "aliases": ["Naikon"]},
  {"ID": "Night Dragon", "entity": "Adversary", "aliases": ["Night Dragon", "Musical Chairs"]},
  {"ID": "OilRig", "entity": "Adversary", "aliases": ["OilRig", "Helix Kitten", "APT(?:| )34"]},
  {"ID": "Orangeworm", "entity": "Adversary", "aliases": ["Orangeworm"]},
  {"ID": "PLATINUM", "entity": "Adversary", "aliases": ["PLATINUM"]},
  {"ID": "PROMETHIUM", "entity": "Adversary", "aliases": ["PROMETHIUM"]},
  {"ID": "Patchwork", "entity": "Adversary", "aliases": ["Patchwork", "Dropping Elephant", "Chinastrats", "MONSOON", "Operation Hangover"]},
  {"ID": "PittyTiger", "entity": "Adversary", "aliases": ["PittyTiger"]},
  {"ID": "Poseidon Group", "entity": "Adversary", "aliases": ["Poseidon Group"]},
  {"ID": "Putter Panda", "entity": "Adversary", "aliases": ["Putter Panda", "APT2", "MSUpdater"]},
  {"ID": "RTM", "entity": "Adversary", "aliases": ["RTM"]},
  {"ID": "Rancor", "entity": "Adversary", "aliases": ["Rancor"]},
  {"ID": "Sandworm Team", "entity": "Adversary", "aliases": ["Sandworm Team", "Quedagh", "VOODOO BEAR"]},
  {"ID": "Scarlet Mimic", "entity": "Adversary", "aliases": ["Scarlet Mimic"]},
  {"ID": "Sowbug", "entity": "Adversary", "aliases": ["Sowbug"]},
  {"ID": "Stealth Falcon", "entity": "Adversary", "aliases": ["Stealth Falcon"]},
  {"ID": "Strider", "entity": "Adversary", "aliases": ["Strider", "ProjectSauron"]},
  {"ID": "Suckfly", "entity": "Adversary", "aliases": ["Suckfly"]},
  {"ID": "TA459", "entity": "Adversary", "aliases": ["TA459"]},
  {"ID": "Taidoor", "entity": "Adversary", "aliases": ["Taidoor"]},
  {"ID": "Threat Group-1314", "entity": "Adversary", "aliases": ["Threat Group-1314", "TG(?:-| |)1314"]},
  {"ID": "Threat Group-3390", "entity": "Adversary", "aliases": ["Threat Group-3390", "TG(?:-| |)3390", "Emissary Panda", "BRONZE UNION", "APT27", "Iron Tiger", "LuckyMouse"]},
  {"ID": "Thrip", "entity": "Adversary", "aliases": ["Thrip"]},
  {"ID": "Turla", "entity": "Adversary", "aliases": ["Turla", "Waterbug", "WhiteBear", "VENOMOUS BEAR", "Snake", "Krypton"]},
  {"ID": "Winnti Group", "entity": "Adversary", "aliases": ["Winnti", "Blackfly"]},
  {"ID": "admin@338", "entity": "Adversary", "aliases": ["admin@338"]},
  {"ID": "menuPass", "entity": "Adversary", "aliases": ["menuPass", "Stone Panda", "APT10", "Red Apollo", "CVNX", "HOGFISH"]},
/*Industry*/
  {"ID": "Agricultre", "entity": "Industry", "aliases": ["(?:Agricultre|Forestry|Fishing|(?:Crop|Animal) Production|Abitoire)\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Aerospace", "entity": "Industry", "aliases": ["(?:Aerospace|Aviation)"]},
  {"ID": "Automotive", "entity": "Industry", "aliases": ["(?:Auto(?:| )motive|Auto(?:| )mobile)"]},
  {"ID": "Communications", "entity": "Industry", "aliases": ["(?:Communication(?:|s))\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Construction", "entity": "Industry", "aliases": ["(?:Construction|Building)\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Defence", "entity": "Industry", "aliases": ["(?:Defence|Defense)\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Education", "entity": "Industry", "aliases": ["(?:Education|School|Schooling)\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Energy", "entity": "Industry", "aliases": ["(?:Energy|Gas|Electricity|Nuclear|Heating)\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Entertainment", "entity": "Industry", "aliases": ["(?:Entertainment|Gaming)\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Financial Services", "entity": "Industry", "aliases": ["(?:Financial Services|Finance|Financial|Bank(?:|[\\w]+))\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Government", "entity": "Industry", "aliases": ["Government\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Healthcare", "entity": "Industry", "aliases": ["(?:Healthcare|Health|Care)\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Hospitality - Leisure", "entity": "Industry", "aliases": ["(?:Hospitality|Leisure)\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Infastructure", "entity": "Industry", "aliases": ["Infastructure\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Insurance", "entity": "Industry", "aliases": ["Insurance\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Manufacturing", "entity": "Industry", "aliases": ["Manufacturing\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Mining", "entity": "Industry", "aliases": ["Mining\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Non-Profit", "entity": "Industry", "aliases": ["(?:Non-Profit|Charity)\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Pharmceuticals", "entity": "Industry", "aliases": ["(?:Pharmceutical|Pharmceuticals)\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Retail", "entity": "Industry", "aliases": ["(?:Retail|Clothes|High Street)\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Technology", "entity": "Industry", "aliases": ["(?:Technology|High Tech)\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Telecommunications", "entity": "Industry", "aliases": ["(?:Telecommunications|Telco|Telecom[\\w]+)\\b.+(?:sector|sectors|industr[\\w]+)"]},
  {"ID": "Transport", "entity": "Industry", "aliases": ["Transport\\b.+(?:sector|sectors|industr[\\w]+)"]},
/*Geography*/
  {"ID": "Afghanistan", "entity": "Country", "aliases": ["Afghanistan(?:|i|'s)"]},
  {"ID": "Angola", "entity": "Country", "aliases": ["Angola(?:|'s)"]},
  {"ID": "Albania", "entity": "Country", "aliases": ["Albania(?:|'s)"]},
  {"ID": "Andorra", "entity": "Country", "aliases": ["Andorra(?:|'s)"]},
  {"ID": "Argentina", "entity": "Country", "aliases": ["Argentina(?:|n|'s)"]},
  {"ID": "Armenia", "entity": "Country", "aliases": ["Armenia(?:|n|'s)"]},
  {"ID": "Austria", "entity": "Country", "aliases": ["Austria(?:|n|'s)"]},
  {"ID": "Azerbaijan", "entity": "Country", "aliases": ["Azerbaijan(?:|i|'s)"]},
  {"ID": "Burundi", "entity": "Country", "aliases": ["Burundi(?:|'s)"]},
  {"ID": "Belgium", "entity": "Country", "aliases": ["Belgium(?:|'s)|Belgian"]},
  {"ID": "Bangladesh", "entity": "Country", "aliases": ["Bangladesh(?:|i|'s)"]},
  {"ID": "Bulgaria", "entity": "Country", "aliases": ["Bulgaria(?:|n|'s)"]},
  {"ID": "Bahrain", "entity": "Country", "aliases": ["Bahrain(?:|i|'s)"]},
  {"ID": "Bahamas", "entity": "Country", "aliases": ["Bahamas"]},
  {"ID": "Bosnia and Herzegovina", "entity": "Country", "aliases": ["Bosnia and Herzegovina"]},
  {"ID": "Belarus", "entity": "Country", "aliases": ["Belarus(?:|')"]},
  {"ID": "Bolivia", "entity": "Country", "aliases": ["Bolivia(?:|n|'s)"]},
  {"ID": "Brazil", "entity": "Country", "aliases": ["Brazil(?:|ian|'s)"]},
  {"ID": "Bhutan", "entity": "Country", "aliases": ["Bhutan"]},
  {"ID": "Botswana", "entity": "Country", "aliases": ["Botswana(?:|n|'s)"]},
  {"ID": "Switzerland", "entity": "Country", "aliases": ["Switzerland(?:|'s)|Swiss"]},
  {"ID": "Chile", "entity": "Country", "aliases": ["Chile(?:|'s)|Chilean"]},
  {"ID": "China", "entity": "Country", "aliases": ["China(?:|'s)|Chinese"]},
  {"ID": "Cote d'Ivoire", "entity": "Country", "aliases": ["Cote d'Ivoire(?:|'s)"]},
  {"ID": "Cameroon", "entity": "Country", "aliases": ["Cameroon(?:|ian|'s)"]},
  {"ID": "Congo", "entity": "Country", "aliases": ["Congo(?:|lese|'s)"]},
  {"ID": "Colombia", "entity": "Country", "aliases": ["Colombia(?:|n|'s)"]},
  {"ID": "Comoros", "entity": "Country", "aliases": ["Comoros"]},
  {"ID": "Cabo Verde", "entity": "Country", "aliases": ["Cabo Verde"]},
  {"ID": "Costa Rica", "entity": "Country", "aliases": ["Costa Rica(?:|n|'s)"]},
  {"ID": "Cuba", "entity": "Country", "aliases": ["Cuba(?:|n|'s)"]},
  {"ID": "Cyprus", "entity": "Country", "aliases": ["Cyprus(?:|')|Cypriot"]},
  {"ID": "Czechia", "entity": "Country", "aliases": ["Czech(?:|'s)"]},
  {"ID": "Germany", "entity": "Country", "aliases": ["German(?:|y|'s)"]},
  {"ID": "Djibouti", "entity": "Country", "aliases": ["Djibouti"]},
  {"ID": "Dominica", "entity": "Country", "aliases": ["Dominica(?:|n|'s)"]},
  {"ID": "Denmark", "entity": "Country", "aliases": ["Denmark(?:|'s)|Danish"]},
  {"ID": "Algeria", "entity": "Country", "aliases": ["Algeria(?:|n|'s)"]},
  {"ID": "Ecuador", "entity": "Country", "aliases": ["Ecuador(?:|ian|'s)"]},
  {"ID": "Egypt", "entity": "Country", "aliases": ["Egypt(?:|ian|'s)"]},
  {"ID": "Eritrea", "entity": "Country", "aliases": ["Eritrea(?:|n|'s)"]},
  {"ID": "Spain", "entity": "Country", "aliases": ["Spain(?:|'s)|Spanish"]},
  {"ID": "Estonia", "entity": "Country", "aliases": ["Estonia(?:|n|'s)"]},
  {"ID": "Ethiopia", "entity": "Country", "aliases": ["Ethiopia(?:|n|'s)"]},
  {"ID": "Finland", "entity": "Country", "aliases": ["Finland(?:|'s)|Finnish"]},
  {"ID": "Fiji", "entity": "Country", "aliases": ["Fiji(?:|an|'s)"]},
  {"ID": "France", "entity": "Country", "aliases": ["France(?:|'s)|French"]},
  {"ID": "Micronesia", "entity": "Country", "aliases": ["Micronesia"]},
  {"ID": "Gabon", "entity": "Country", "aliases": ["Gabon(?:|ese|'s)"]},
  {"ID": "United Kingdom", "entity": "Country", "aliases": ["Brit(?:ain|ish)(?:|'s)|United Kingdom(?:|'s)|UK(?:|'s)| U\\.K(?:|\\.)(?:|'s)"]},
  {"ID": "Ghana", "entity": "Country", "aliases": ["Ghana(?:|'s)|Ghanian"]},
  {"ID": "Guinea", "entity": "Country", "aliases": ["^(?:(?!New|Equitorial).)*Guinea.*"]},
  {"ID": "Gambia", "entity": "Country", "aliases": ["Gambia(?:|n|'s)"]},
  {"ID": "Guinea-Bissau", "entity": "Country", "aliases": ["Guinea-Bissau"]},
  {"ID": "Equatorial Guinea", "entity": "Country", "aliases": ["Equatorial Guinea"]},
  {"ID": "Greece", "entity": "Country", "aliases": ["Greece(?:|'s)|Greek"]},
  {"ID": "Guatemala", "entity": "Country", "aliases": ["Guatemala(?:|n|'s)"]},
  {"ID": "Guyana", "entity": "Country", "aliases": ["Guyana(?:|n|'s)"]},
  {"ID": "Hong Kong", "entity": "Country", "aliases": ["Hong Kong(?:|'s)"]},
  {"ID": "Honduras", "entity": "Country", "aliases": ["Honduras"]},
  {"ID": "Croatia", "entity": "Country", "aliases": ["Croatia(?:|n|'s)"]},
  {"ID": "Haiti", "entity": "Country", "aliases": ["Haiti(?:|an|'s)"]},
  {"ID": "Hungary", "entity": "Country", "aliases": ["Hungary(?:|'s)|Hungarian"]},
  {"ID": "Indonesia", "entity": "Country", "aliases": ["Indonesia(?:|n|'s)"]},
  {"ID": "India", "entity": "Country", "aliases": ["India(?:|n|'s)"]},
  {"ID": "Iran", "entity": "Country", "aliases": ["Iran(?:|ian|'s)"]},
  {"ID": "Iraq", "entity": "Country", "aliases": ["Iraq(?:|i|'s)"]},
  {"ID": "Iceland", "entity": "Country", "aliases": ["Iceland(?:|ic|'s)"]},
  {"ID": "Israel", "entity": "Country", "aliases": ["Israel(?:|i|'s)"]},
  {"ID": "Italy", "entity": "Country", "aliases": ["Italy(?:|'s)|Italian"]},
  {"ID": "Jordan", "entity": "Country", "aliases": ["Jordan(?:|'s)|Jordanian"]},
  {"ID": "Kazakhstan", "entity": "Country", "aliases": ["Kazakhstan(?:|i|'s)"]},
  {"ID": "Kenya", "entity": "Country", "aliases": ["Kenya(?:|n|'s)"]},
  {"ID": "Kyrgyzstan", "entity": "Country", "aliases": ["Kyrgyzstan(?:|i|'s)"]},
  {"ID": "Cambodia", "entity": "Country", "aliases": ["Cambodia(?:|n|'s)"]},
  {"ID": "Kiribati", "entity": "Country", "aliases": ["Kiribati"]},
  {"ID": "Kuwait", "entity": "Country", "aliases": ["Kuwait(?:|i|'s)"]},
  {"ID": "Lebanon", "entity": "Country", "aliases": ["Lebanon(?:|'s)|Lebanese"]},
  {"ID": "Liberia", "entity": "Country", "aliases": ["Liberia(?:|n|'s)"]},
  {"ID": "Libya", "entity": "Country", "aliases": ["Libya(?:|n|'s)"]},
  {"ID": "Liechtenstein", "entity": "Country", "aliases": ["Liechtenstein(?:|'s)"]},
  {"ID": "Sri Lanka", "entity": "Country", "aliases": ["Sri Lanka(?:|n|'s)"]},
  {"ID": "Lesotho", "entity": "Country", "aliases": ["Lesotho(?:|'s)"]},
  {"ID": "Lithuania", "entity": "Country", "aliases": ["Lithuania(?:|n|'s)"]},
  {"ID": "Luxembourg", "entity": "Country", "aliases": ["Luxembourg(?:|'s)"]},
  {"ID": "Latvia", "entity": "Country", "aliases": ["Latvia(?:|'s)|Latvian"]},
  {"ID": "Macao", "entity": "Country", "aliases": ["Macao"]},
  {"ID": "Morocco", "entity": "Country", "aliases": ["Morocco(?:|'s)|Morroccan"]},
  {"ID": "Monaco", "entity": "Country", "aliases": ["Monaco(?:|'s)"]},
  {"ID": "Moldova, Republic of", "entity": "Country", "aliases": ["Moldova(?:|n|'s)"]},
  {"ID": "Madagascar", "entity": "Country", "aliases": ["Madagascar(?:|'s)|Madagascan"]},
  {"ID": "Maldives", "entity": "Country", "aliases": ["Maldives(?:|')"]},
  {"ID": "Mexico", "entity": "Country", "aliases": ["Mexico(?:|'s)|Mexican"]},
  {"ID": "Marshall Islands", "entity": "Country", "aliases": ["Marshall Islands"]},
  {"ID": "Macedonia", "entity": "Country", "aliases": ["Macedonia(?:|'s)"]},
  {"ID": "Mali", "entity": "Country", "aliases": ["Mali(?:|'s)"]},
  {"ID": "Malta", "entity": "Country", "aliases": ["Malta(?:|'s)|Maltese"]},
  {"ID": "Myanmar", "entity": "Country", "aliases": ["Myanmar|Burma"]},
  {"ID": "Montenegro", "entity": "Country", "aliases": ["Montenegro(?:|'s)"]},
  {"ID": "Northern Mariana Islands", "entity": "Country", "aliases": ["Northern Mariana"]},
  {"ID": "Mozambique", "entity": "Country", "aliases": ["Mozambique(?:|'s)"]},
  {"ID": "Mauritania", "entity": "Country", "aliases": ["Mauritania"]},
  {"ID": "Mauritius", "entity": "Country", "aliases": ["Mauritius(?:|')"]},
  {"ID": "Malawi", "entity": "Country", "aliases": ["Malawi(?:|'s)"]},
  {"ID": "Namibia", "entity": "Country", "aliases": ["Namibia(?:|n|'s)"]},
  {"ID": "Niger", "entity": "Country", "aliases": ["Niger(?:|'s)"]},
  {"ID": "Nigeria", "entity": "Country", "aliases": ["Nigeria(?:|n|'s)"]},
  {"ID": "Nicaragua", "entity": "Country", "aliases": ["Nicaragua(?:|'s)"]},
  {"ID": "Niue", "entity": "Country", "aliases": ["Niue"]},
  {"ID": "Netherlands", "entity": "Country", "aliases": ["Netherlands(?:|')|Dutch"]},
  {"ID": "Norway", "entity": "Country", "aliases": ["Norway(?:|'s)|Norwegian"]},
  {"ID": "Nepal", "entity": "Country", "aliases": ["Nepal(?:|'s)|Nepalese"]},
  {"ID": "Nauru", "entity": "Country", "aliases": ["Nauru"]},
  {"ID": "Oman", "entity": "Country", "aliases": ["Oman(?:|i|'s)"]},
  {"ID": "Pakistan", "entity": "Country", "aliases": ["Pakistan(?:|i)"]},
  {"ID": "Panama", "entity": "Country", "aliases": ["Panama"]},
  {"ID": "Peru", "entity": "Country", "aliases": ["Peru(?:|'s)"]},
  {"ID": "Philippines", "entity": "Country", "aliases": ["Philippines(?:|')"]},
  {"ID": "Palau", "entity": "Country", "aliases": ["Palau"]},
  {"ID": "Papua New Guinea", "entity": "Country", "aliases": ["Papua New Guinea"]},
  {"ID": "Poland", "entity": "Country", "aliases": ["Poland|Polish"]},
  {"ID": "North Korea", "entity": "Country", "aliases": ["Democratic People's Republic of Korea|North Korea(?:|n)"]},
  {"ID": "Portugal", "entity": "Country", "aliases": ["Portugal|Portugese"]},
  {"ID": "Paraguay", "entity": "Country", "aliases": ["Paraguay"]},
  {"ID": "Palestine", "entity": "Country", "aliases": ["Palestine(?:|'s)|Palestinian"]},
  {"ID": "Qatar", "entity": "Country", "aliases": ["Qatar(?:|i|'s)"]},
  {"ID": "Rwanda", "entity": "Country", "aliases": ["Rwanda"]},
  {"ID": "Saudi Arabia", "entity": "Country", "aliases": ["Saudi(?:|'s)|KSA"]},
  {"ID": "Sudan", "entity": "Country", "aliases": ["^(?:(?!South).)*Sudan(?:|i|'s).*"]},
  {"ID": "Senegal", "entity": "Country", "aliases": ["Senegal(?:|i)"]},
  {"ID": "Singapore", "entity": "Country", "aliases": ["Singapore(?:|an)"]},
  {"ID": "Sierra Leone", "entity": "Country", "aliases": ["Sierra Leone"]},
  {"ID": "El Salvador", "entity": "Country", "aliases": ["El Salvador"]},
  {"ID": "San Marino", "entity": "Country", "aliases": ["San Marino"]},
  {"ID": "Somalia", "entity": "Country", "aliases": ["Somali(?:|a|'s)"]},
  {"ID": "Serbia", "entity": "Country", "aliases": ["Serbia(?:|n|'s)"]},
  {"ID": "South Sudan", "entity": "Country", "aliases": ["South Sudan(?:|i|'s)"]},
  {"ID": "Sao Tome and Principe", "entity": "Country", "aliases": ["Sao Tome"]},
  {"ID": "Suriname", "entity": "Country", "aliases": ["Suriname"]},
  {"ID": "Slovakia", "entity": "Country", "aliases": ["Slovakia(?:|n|'s)"]},
  {"ID": "Slovenia", "entity": "Country", "aliases": ["Slovenia(?:|n|'s)"]},
  {"ID": "Sweden", "entity": "Country", "aliases": ["Sweden(?:|'s)|Swedish"]},
  {"ID": "Swaziland", "entity": "Country", "aliases": ["Swaziland"]},
  {"ID": "Sint Maarten", "entity": "Country", "aliases": ["Sint Maarten"]},
  {"ID": "Seychelles", "entity": "Country", "aliases": ["Seychelles"]},
  {"ID": "Chad", "entity": "Country", "aliases": ["Chad"]},
  {"ID": "Togo", "entity": "Country", "aliases": ["Togo"]},
  {"ID": "Thailand", "entity": "Country", "aliases": ["Thailand(?:|'s)|Thai"]},
  {"ID": "Tajikistan", "entity": "Country", "aliases": ["Tajikistan(?:|i|'s)"]},
  {"ID": "Timor-Leste", "entity": "Country", "aliases": ["Timor-Leste|Timor Leste"]},
  {"ID": "Tonga", "entity": "Country", "aliases": ["Tonga(?:|n|'s)"]},
  {"ID": "Trinidad and Tobago", "entity": "Country", "aliases": ["Trinidad and Tobago"]},
  {"ID": "Tunisia", "entity": "Country", "aliases": ["Tunisia(?:|n|'s)"]},
  {"ID": "Turkey", "entity": "Country", "aliases": ["Turkey(?:|'s')|Turkish"]},
  {"ID": "Taiwan, Province of China", "entity": "Country", "aliases": ["Taiwan(?:|'s)|Taiwanese"]},
  {"ID": "Tanzania, United Republic of", "entity": "Country", "aliases": ["Tanzania(?:|n|'s)"]},
  {"ID": "Uganda", "entity": "Country", "aliases": ["Uganda(?:|n|'s)"]},
  {"ID": "Uruguay", "entity": "Country", "aliases": ["Uruguay(?:|'s)"]},
  {"ID": "United States", "entity": "Country", "aliases": ["America(?:|'s)|U\\.S\\.A|U\\.S\\.|United States(?:|')"]},
  {"ID": "Uzbekistan", "entity": "Country", "aliases": ["Uzbekistan(?:|i|'s)"]},
  {"ID": "Venezuela", "entity": "Country", "aliases": ["Venezuela(?:|n|'s)"]},
  {"ID": "Virgin Islands", "entity": "Country", "aliases": ["Virgin Islands|British Virgin Islands"]},
  {"ID": "Viet Nam", "entity": "Country", "aliases": ["Viet Nam(?:|'s)|Vietnam(?:|ese|'s)"]},
  {"ID": "Vanuatu", "entity": "Country", "aliases": ["Vanuatu"]},
  {"ID": "Samoa", "entity": "Country", "aliases": ["Samoa(?:|n|'s)"]},
  {"ID": "Yemen", "entity": "Country", "aliases": ["Yemen(?:|'s)|Yemni"]},
  {"ID": "South Africa", "entity": "Country", "aliases": ["South (?:Africa(?:|'s)|African)"]},
  {"ID": "Zambia", "entity": "Country", "aliases": ["Zambia(?:|n|'s)"]},
  {"ID": "Zimbabwe", "entity": "Country", "aliases": ["Zimbabwe(?:|'s)"]}
]

chrome.runtime.onMessage.addListener(gotMessage);

function gotMessage(request, sender, sendResponse) {
  if (request.txt === 'Stratus-activate') {
    var identified = []
    var item_json = []
    var innerText = document.body.innerText
    var regexSearchSentences = /[^\.\!\?\:\r\n]*[\.\!\?\;\r\n]/g
    let sentenceList = innerText.match(regexSearchSentences)
    newData.forEach(function(item){
      item.properties.forEach(function(prop) {
        let regexSearchProperty = new RegExp('\\b' + prop + '\\b', "gi")
        if (innerText.match(regexSearchProperty)) {
          if (identified.includes(item.ID) === false) {
            item["match"] = innerText.match(regexSearchProperty)[0];
            identified.push(item.ID);
            item_json.push(item);
          }
          let change = '<span title="' + item.name + ' (' + item.ID + ')' + '"><mark>' + prop + '</mark></span>';
          document.body.outerHTML = document.body.outerHTML.replace(prop, change);
        }
      })
      item.stem.forEach(function(stem) {
        let regexSearchStem = new RegExp('\\b' + stem + '\\b', "gi")
        if (innerText.match(regexSearchStem)) {
          if (identified.includes(item.ID) === false) {
            item["match"] = innerText.match(regexSearchStem)[0];
            identified.push(item.ID);
            item_json.push(item);
          }
        let stemMatch = document.body.innerText.match(regexSearchStem);
        let stemChange = '<span title="' + item.name + ' (' + item.ID + ')' + '"><mark>' + stemMatch + '</mark></span>';
        document.body.outerHTML = document.body.outerHTML.replace(stemMatch, stemChange);
        }
      });
      item.keyword.forEach(function(indicator) {
        let regexSearchIndicator = new RegExp('\\b' + indicator + '\\b', "gi")
        sentenceList.forEach(function(sentence) {
          if (sentence.match(regexSearchIndicator)) {
            item.support.forEach(function(support) {
              let regexSearchSupport = new RegExp('\\b' + support + '\\b', "gi")
              if (sentence.match(regexSearchSupport)) {
                let sentenceChange = '<span title="' + item.name + ' (' + item.ID + ')' + '" style="background-color: #30fff8">' + sentence + '</span>'
                document.body.outerHTML = document.body.outerHTML.replace(sentence, sentenceChange);
                if (identified.includes(item.ID) === false) {
                  item["match"] = sentence;
                  identified.push(item.ID);
                  item_json.push(item);
                }
              }
            })
          }
        })
      })
    });
    entityList.forEach(function(identity) {
      identity.aliases.forEach(function(entity) {
        let regexSearchEntity = new RegExp("\\b" + entity + "(?:|'s)\\b", "gi")
        if (innerText.match(regexSearchEntity)) {

          if (identified.includes(identity.ID) === false) {
            identity["match"] = innerText.match(regexSearchEntity)[0];
            identified.push(identity.ID);
            item_json.push(identity);
            let entityMatch = document.body.innerText.match(regexSearchEntity);
            let entityChange = '<span title="' + identity.ID + '"><mark>' + entityMatch + '</mark></span>';
            document.body.outerHTML = document.body.outerHTML.replace(entityMatch, entityChange);
          }
        }
      })
    });
    chrome.runtime.sendMessage({
                  data: item_json
              }, function (response) {
              });
  };
};
